### DISCUSSION TITLE
Docker does not start when using swagger-ui image in docker

### DISCUSSION THREAD

**Discussion by shiga-takaya-2** [swagger-api/swagger-ui#9347] [Q&A]
I want to use my own openapi.yaml file and display it as swagger-ui.

The local environment directory is as follows:
├── swagger
│   └── openapi.yaml
└── dockerfile
└── docker-compose.yaml

The dockerfile is as follows.

```
FROM swaggerapi/swagger-ui:latest
COPY ./swagger/openapi.yaml /usr/share/nginx/html/openapi.yaml
ENV SWAGGER_JSON /usr/share/nginx/html/openapi.yaml

```
After docker run, when checking docker logs, the following error is displayed and docker does not start. Please tell me the reason and solution.

```
/docker-entrypoint.sh: Launching /docker-entrypoint.d/40-swagger-ui.sh
cp: '/usr/share/nginx/html/openapi.yaml' and '/usr/share/nginx/html/openapi.yaml' are the same file

```
In addition, the contents of 40-swagger-ui.sh are as follows.

```
#! /bin/sh

set -e
NGINX_ROOT=/usr/share/nginx/html
INITIALIZER_SCRIPT=$NGINX_ROOT/swagger-initializer.js
NGINX_CONF=/etc/nginx/conf.d/default.conf

node /usr/share/nginx/configurator $INITIALIZER_SCRIPT


if [ "$SWAGGER_JSON_URL" ]; then
  sed -i "s|https://petstore.swagger.io/v2/swagger.json|$SWAGGER_JSON_URL|g" $INITIALIZER_SCRIPT
  sed -i "s|http://example.com/api|$SWAGGER_JSON_URL|g" $INITIALIZER_SCRIPT
fi

if [[ -f "$SWAGGER_JSON" ]]; then
  cp -s "$SWAGGER_JSON" "$NGINX_ROOT"
  REL_PATH="./$(basename $SWAGGER_JSON)"

  if [[ -z "$SWAGGER_ROOT" ]]; then
    SWAGGER_ROOT="$(dirname $SWAGGER_JSON)"
  fi

  if [[ "$BASE_URL" != "/" ]]
  then
    BASE_URL=$(echo $BASE_URL | sed 's/\/$//')
    sed -i \
      "s|#SWAGGER_ROOT|rewrite ^$BASE_URL(/.*)$ \$1 break;\n        #SWAGGER_ROOT|" \
      $NGINX_CONF
  fi
  sed -i "s|#SWAGGER_ROOT|root $SWAGGER_ROOT/;|g" $NGINX_CONF

  sed -i "s|https://petstore.swagger.io/v2/swagger.json|$REL_PATH|g" $INITIALIZER_SCRIPT
  sed -i "s|http://example.com/api|$REL_PATH|g" $INITIALIZER_SCRIPT
fi

# enable/disable the address and port for IPv6 addresses that
```

◆supplement
Container up using docker-compose was successful.
docker-compose.yaml is as follows. This time, I want to make sure to replace the volumes in docker-compose.yaml with the COPY command in the dockerfile.
```
version: '3.9'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8080:8080"
    volumes:
      - ./swagger/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml

```

**Comment by SergioSboy** [comment]
Hi! Did you solve this problem?

**Comment by lharzenetter** [comment]
Worked for me like that:

```yaml
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8080:8080"
    volumes:
      - ./swagger/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://swagger-ui:8080/readiness"]
      interval: 200s
      timeout: 200s
      retries: 5
```

Credits to [Thanh Nguyen Van](https://stackoverflow.com/a/59062794/6592788)
