### ISSUE TITLE
Array of multi-value prameters are always sent as muliple parameters instances

### ISSUE THREAD

**Issue by piotrwalczak1** [swagger-api/swagger-ui#10023]
Regardless of collectionFormat setting (default is csv - comman separated), when the parameters are defined as an array of strings, always multiple instances are sent istead of comma separated ones.

### Q&A (please complete the following information)
 - OS: WIndows, linux
 - Browser: chrome, firefox
 - Version: 126.0
 - Method of installation: npm
 - Swagger-UI version: 3.0.1
 - Swagger/OpenAPI version: 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
 parameters:
        - name: "myParameter"
          in: query
          description: array of items
          required: true
          allowEmptyValue: false
          schema:
            type: array
            collectionFormat: csv
            items:
              type: string
          example:
            - 'ABC'
            - 'DEF'
```

This is sent as:
```js
check?myParameter=ABC&myParameter=DEF'
```

Should be sent as
```
check?myParameter=ABC,DEF
```
