### ISSUE TITLE
BUG: failing to fetch examples for parameters

### ISSUE THREAD

**Issue by destinedcodes** [swagger-api/swagger-ui#10121]
### Q&A (please complete the following information)
 - OS: ArchLinux
 - Browser: chrome
 - Version: 127.0.6533.99 (Official Build) (64-bit)
 - Method of installation: Swagger editor
 - Swagger-UI version: 3.10.0
 - Swagger/OpenAPI version: OpenAPI 3.1.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
  /api/resource/User:
    get:
      tags:
        - user
      summary: "Get All Users"
      description: "Retrieve a list of all User records."
      parameters:
        - name: fields
          in: query
          description: "Comma-separated list of fields to include in the response."
          schema:
            type: string
            examples: 
              - 'field'
```

### Describe the bug you're encountering

Swagger UI doesn't use example or parameter when using the **examples** key (as an array). I got it to work using the deprecated **example**

### To reproduce...

1. write a sample swagger yaml in swagger editor
2. add a path and add a param field.
3. add example `example` to the properties and you can see the example value.
4. replace with examples as an array and you'd lose the example value

### Expected behavior

should be able to render the example vaue when using examples

### Screenshots

![image](https://github.com/user-attachments/assets/14355ee1-99e4-4c9c-84fd-7d392346ef2c)
![image](https://github.com/user-attachments/assets/6eb9afb9-0258-485b-95a5-758d9b7bcbea)

### Additional context or thoughts

Willing to attempt fixing this - if it gets approved to be a bug
