### ISSUE TITLE
display constraints from x-field-extra-annotation parameter of Swagger/OpenAPI definition

### ISSUE THREAD

**Issue by mbesurich** [swagger-api/swagger-ui#10246]
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
components:
  schemas:
    SomeDto:
      required:
        - someProperty
      type: object
      properties:
        someProperty:
          type: string
          x-field-extra-annotation:
                - "@jakarta.validation.constraints.NotEmpty"
               - "@org.hibernate.validator.constraints.UUID(allowNil = false)"
  ```

 Swagger-UI configuration options:
 ```js
 SwaggerUI({
   // your config options here
 })
 ```

 ```
 ?yourQueryStringConfig
 ```

### Is your feature request related to a problem?
I use openapi-generator-maven-plugin to build DTO and Controller classes. I have to put some constraint annotations into x-field-extra-annotation of a parameter. But When I run the application I do not see these  constraint annotations in swagger-ui. 

### Describe the solution you'd like
I want that swagger-ui displays values of x-field-extra-annotation for assosiated parameters of dto.

### Describe alternatives you've considered
I tried to "override" indeh.html, and write there custom js plug whicj could display at least names on annotations from x-field-extra-annotation. But I figured out that swagger-ui does not receive any information from Swagger/OpenAPI definition .yaml file which is not shown in swagger-ui. I mean the dto's property does not contain x-field-extra-annotation parateters at all.
