### ISSUE TITLE
deepObject query parameter does not work

### ISSUE THREAD

**Issue by siddhsql** [swagger-api/swagger-ui#10245]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: chrome
 - Version: 131.0
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: not sure. I am using
```
<dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <version>2.5.0</version>
      <scope>runtime</scope>
   </dependency>   
```
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0] openapi: 3.0.1

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
parameters:        
        - name: metadata
          in: query
          required: false
          style: deepObject
          explode: true
          schema:
            type: object
            additionalProperties:
              type: string        
```

full config is omitted to show just the part in question

### Describe the bug you're encountering
I do not see any field for metadata in the UI

![image](https://github.com/user-attachments/assets/de42116b-43c3-4c68-b103-ee0d1efd2db7)

### To reproduce...
- declare a query parameter of type `deepObject`
- open Swagger UI

### Expected behavior
I should be seeing a field to enter metadata information

### Screenshots
![image](https://github.com/user-attachments/assets/6e29e726-494f-4887-817e-74a142b527e4)

### Additional context or thoughts
https://github.com/swagger-api/swagger-ui/issues/4216
