### ISSUE TITLE
Set Access-Control-Allow-Origin headers when running from docker image

### ISSUE THREAD

**Issue by CameronGo** [swagger-api/swagger-ui#10275]
### Q&A (please complete the following information)
 - Method of installation: docker hub image
 - Swagger-UI version: v5.18.3

### Content & configuration

Swagger-UI configuration options:
docker compose file used to run swagger ui
```yaml
services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.18.3
    ports:
      - "8080:8080"
    environment:
      - DEEP_LINKING=true
      - DISPLAY_REQUEST_DURATION=true
      - OAUTH_USE_PKCE=true
      - DOC_EXPANSION=none
```

### How can we help?
When I run swagger-ui from the published docker image, the response headers include `Access-Control-Allow-Origin: *`. I'd like to set this so that it includes only my API domain name. Is this possible? Every CORS related question I've seen seems to revolve around the openapi.yaml file, not the swagger UI web application itself.

My swagger-ui is running behind the same hostname as my API so I don't really need this header to allow anything for my use case and would just as soon set it to its strictest value.
