### ISSUE TITLE
dist/swagger-ui.css emits wrong selectors

### ISSUE THREAD

**Issue by sant123** [swagger-api/swagger-ui#10355]
Hello, taking a look at [dist/swagger-ui.css](https://github.com/swagger-api/swagger-ui/blob/master/dist/swagger-ui.css) it has selectors like:

```css
.swagger-ui html {
  line-height: 1.15;
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
}
.swagger-ui body {
  margin: 0;
}
```

Is this expected? For making the body styling work, a classname called `swagger-ui` should be set there. However the docs don't mention [it](https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/usage/installation.md#unpkg).

Thanks.
