### ISSUE TITLE
Swagger UI remove automatically text input ".0" from multipart

### ISSUE THREAD

**Issue by sinattieng** [swagger-api/swagger-ui#10415]
Good evening,

I am writing this issue because my spring-boot application which is using swagger-ui compoments has no longer capable to inject on my java bean this inpurt part from multipart object :

``` 

@Schema(type = SchemaType.STRING, required = true, description = "Versione dell'xml versato (versione SIP)", examples = "3.0")
    @FormParam("VERSIONE")
    @PartType(MediaType.TEXT_PLAIN)
    @NotEmpty(message = "Necessario indicare il campo VERSIONE")
    public String VERSIONE;

```

filed "VERSIONE" in case of value **3.0** results as **3** without .0 injected on field, it happens only with this particularly value (it seems automatically accept natural number in this case BUT if i try with 3.1 is correct).

What should I do ? 

Thank you in advance for the support.

Stefano

**Comment by char0n** [comment]
Hi @sinattieng,

Could you provide the API Description that results from your annotations? If the resulting `examples` keyword will look like this:

```yaml
examples: 
  - "3.0"
```

then it's not going by to parsed (or shouldn't be) by the SwaggerUI as a number. The error is for sure comming from the fact that your "3.0" is parsed as a number, which in JavaScript result in just `3`.

**Comment by sinattieng** [comment]
Hi @char0n 

Below what you ask for: 

```
    VersamentoFascicoloOauth2MultipartForm:
      required:
      - VERSIONE
      - XMLSIP
      type: object
      properties:
        VERSIONE:
          description: Versione dell'xml versato (versione SIP)
          minLength: 1
          type: string
          example: "3.0"
        XMLSIP:
          description: Xml versato
          type: object
          properties:
            IndiceSIPFascicolo:
              minLength: 1
              example: <IndiceSIPFascicolo></IndiceSIPFascicolo>
    VersamentoFascicoloStdMultipartForm:
      required:
      - VERSIONE
      - LOGINNAME
      - PASSWORD
      - XMLSIP
      type: object
      properties:
        VERSIONE:
          description: Versione dell'xml versato (versione SIP)
          minLength: 1
          type: string
          example: "3.0"
        LOGINNAME:
          description: Userid dell'utente versatore
          minLength: 1
          type: string
          example: login
        PASSWORD:
          format: password
          description: Password dell'utente versatore
          minLength: 1
          type: string
          example: password
        XMLSIP:
          description: Xml versato
          type: object
          properties:
            IndiceSIPFascicolo:
              minLength: 1
              example: <IndiceSIPFascicolo></IndiceSIPFascicolo>
```
