### ISSUE TITLE
OpenApi 3.1 Data Type support

### ISSUE THREAD

**Issue by JCamargo-onlocation** [swagger-api/swagger-ui#10501]
### Content & configuration
Display the data types as previously.
We have a lot of DTOs that may be similar in structure, and different DTOs tailored to each endpoint to improve performance, so missing the data type, specially in arrays makes it difficult to quickly find the DTO as not we need to first find the endpoint and then the response object.
We have the $ref object in the yaml, so the data should be there as previously.

Feel free to point me to an existing issue, I couldn't find if this was already reported.

Swagger/OpenAPI definition:
 ```yaml
 "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ResaleEventDto"
              }
            }
          },
          "required": true
        }
 ```
