### ISSUE TITLE
Multiple examples inside schema

### ISSUE THREAD

**Issue by msosnicki** [swagger-api/swagger-ui#10503]
## Context
OpenAPI spec 3.1 announced support for [multiple examples inside a schema](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0#:~:text=Use%20examples%20not%20example) (not to be confused with multiple examples for request/response which has been supported for a while now).
I was trying to check out how this feature looks like, but it seems is not yet supported by SwaggerUI latest version (`5.2.4` as of now).

## Specs

The following, single example syntax is supported at `3.0.2`:
 ```yaml
components:
  schemas:
    Cat:
      type: object
      required: [name, livesLeft]
      properties:
        name:
          type: string
        livesLeft:
          type: integer
      example:
        name: Grumpy
        livesLeft: 2
 ```

It renders 

![Image](https://github.com/user-attachments/assets/9e96db16-277f-4bb6-8c76-0abd37596df4)

However, if I try to switch to `3.1.0` and use multiple examples
```yaml
components:
  schemas:
    Cat:
      type: object
      required: [name, livesLeft]
      properties:
        name:
          type: string
        livesLeft:
          type: integer
      examples:
        - name: Grumpy
          livesLeft: 2
        - name: Felix
          livesLeft: 3
```

the following is rendered

![Image](https://github.com/user-attachments/assets/59449629-94e2-47aa-a635-2f0962a2629c)

Which is incorrect, as it looks as if `Examples` was a property of a `Cat` object.

 Are there any plans to add support for this feature? Thanks
