### ISSUE TITLE
Is it possible to have a parameter of type "query" where multiple values (list) can be given?

### ISSUE THREAD

**Issue by pietervogelaar** [swagger-api/swagger-ui#118]
I have a query parameter for an operation that is a filter. But the API accepts this parameter as array, so with multiple values.

Is it possible to fill multiple values in Swagger UI? If yes, how?

**Comment by mjgp2** [comment]
This seems to have been implemented in the spec now (example below), but not in the UI?

```
        - name: input
          in: query
          required: false
          type: array
          collectionFormat: multi
          items:
            type: string
```
