### ISSUE TITLE
Support apiKey in header

### ISSUE THREAD

**Issue by hongyes** [swagger-api/swagger-ui#1393]
Some definition like:
```yaml
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
```
It won't work in swagger UI as the apiKey will be sent by query string by default. Since the information is already in swagger document. It should be feasible for the UI client to determine where to put the api key.
