### ISSUE TITLE
Try It out not working when two parameters of different type have the same name

### ISSUE THREAD

**Issue by rubenmch** [swagger-api/swagger-ui#1445]
If an operation has two parameters with the same name but different location (type), the Try It out button uses the same value for both parameters instead of sending each with its own value. It uses the value of the last parameter for both types.

The swagger 2 specification says:

```
A unique parameter is defined by a combination of a name and location.
```

We have an existing API that uses the query parameters to filter the data to be updated and the form parameters to assign the new values in a PUT operation.

How to reproduce:
1. Declare a PUT operation with the following Parameters:
   
   ``` yaml
   -
            name: Name
            in: query
            type: string
   -
            name: Name
            in: formData
            type: string
   ```
2.  In Swagger UI fill the **query Name** parameter with the value **QueryName**
3. Fill the **formData Name** parameter with the value **FormDataName**
4. Click the Try It out! button

Result:

The formData and the query parameters will be sent with the value **FormDataName**

Expected result:

The **query Name** parameter is sent with the value **QueryName**
The **formData Name**  parameter is sent with the value **FormDataName**
