### ISSUE TITLE
Place holder for query csv param is wrong

### ISSUE THREAD

**Issue by GiladShoham** [swagger-api/swagger-ui#1749]
Hi,
currently when you have a query param of type csv:

``` yaml
      - in: query
        description: ids array
        name: ids
        required: false
        type: array
        collectionFormat: csv
        items:
          type: string
```

The place holder in swagger ui says:

```
Provide multiple values in new lines.
```

But when you put the values in new lines it's not working.
it only working with comma separation and without new lines.

so need to change the placeholder or make it work with new lines.
