### ISSUE TITLE
XML Generation does not calculate root tag name correctly

### ISSUE THREAD

**Issue by JessieAMorris** [swagger-api/swagger-ui#1982]
If I create a response schema to be used for XML then Swagger UI shows an error that:

```
<?xml version="1.0"?>
<!-- invalid XML: Node name is not provided -->
```

This is despite having my schema named.

For example, the following schema does not work:

```
    authentication:
        type: object
        properties:
            response_code:
                type: integer
            message:
                type: string
            token:
                type: string
```

but if I add the xml name to it it works correctly:

```
    authentication:
        type: object
        properties:
            response_code:
                type: integer
            message:
                type: string
            token:
                type: string
      xml:
         name: authentication
```

**Comment by webron** [comment]
@bodnia can you please look at that?

**Comment by bodnia** [comment]
@JessieAMorris I tried schema you provided, please see the results I got:
When placing this into definitions:
```
definitions:
  authentication:
    type: object
    properties:
      response_code:
        type: integer
      message:
        type: string
      token:
        type: string
```

and then referring to it in schema:
```
schema:
  $ref: "#/definitions/authentication"
``` 
then the result is 
![XML example](https://cloud.githubusercontent.com/assets/8950657/13253436/be891a9c-da44-11e5-9979-c2510eecb163.png)

As per [specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object) on top level in schema object there are following properties supported:

> $ref - As a JSON Reference
format (See Data Type Formats for further details)
title
description (GFM syntax can be used for rich text representation)
default (Unlike JSON Schema, the value MUST conform to the defined type for the Schema Object)
multipleOf
maximum
exclusiveMaximum
minimum
exclusiveMinimum
maxLength
minLength
pattern
maxItems
minItems
uniqueItems
maxProperties
minProperties
required
enum
type

So the correctly schema would appear in case of adding 
```
xml : 
  name: 'your_custom_name'
```
to define a root node name of xml example. 
Also there is an [example](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#simple-model) of simple model in specification.

@webron Does this make sense?
