### ISSUE TITLE
[Question] Display JSON model including the root value

### ISSUE THREAD

**Issue by hiveship** [swagger-api/swagger-ui#1988]
I have specified my existing API using Swagger. Now I'm facing a little problem with Swagger UI and I need some help to configure it.

For example, I have a model definition declared as below:

```yaml
  medium:
    properties:
      name: 
        type: string
      status:
      type:
       type: string
```

The output in the Swagger UI is:

```json
{
  "name": "string",
  "type": "foo"
}
```

It's correct BUT in my implementation, I'm expecting to get the JSON with the "root element/value" value, such:

```json
{
**  "Medium": {**
       "name": "string",
       "type": "foo"
   }
}
```
(For specific reasons, I can't change the implementation of my API).

How can I configure Swagger UI (or maybe I need to edit my swagger.yaml (ok with that), to **display the JSON model using the root element/value **?
If it's not currently supported, can you give me some help and I may try to do it and then send a PR ?
