### ISSUE TITLE
"Cannot read property 'toLowerCase' of undefined" in ParameterView

### ISSUE THREAD

**Issue by patrickhulce** [swagger-api/swagger-ui#2004]
Rendering a swagger doc that contains a body parameter with the following properties, fails with error
"Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
(anonymous function)    @   index.js:24
Handlebars.templates.param_list.Handlebars.template.main    @   client.js:374
e   @   handlebars-2.0.0.js:27
SwaggerUi.Views.ParameterView.Backbone.View.extend.render   @   index.js:24"

```
- name: foo
  in: body
  required: true
  schema:
    type: boolean
```
