### ISSUE TITLE
Swagger Not sending array correctly

### ISSUE THREAD

**Issue by itabrezshaikh** [swagger-api/swagger-ui#2067]
Hi,

I am trying to send multiple values (an array) (refer to on line 93 in spec ->... name: recipients[] ...)

The problem I am facing is the Swagger-ui call the endpoints as below:

**Actual**
 recipients[]=value1%2Cvalue2 

**Expected**
recipients[]=value1&recipients[]=value2

The %2C means , (comma).

Please help/guide, its urgent. 

Thanks,
Tabby

Below are the required details:
- swagger-ui version 2.1.1
- a swagger file reproducing the issue (attached)

[pepipost.dev.v4.yaml.txt](https://github.com/swagger-api/swagger-ui/files/197320/pepipost.dev.v4.yaml.txt)

**Comment by webron** [comment]
You need to set the collectionFormat.

```yaml
        - name: recipients[]
          in: formData
          description: Email addresses for recipients (multiple values allowed).
          required: true
          collectionFormat: multi
          type: array
          items:
              type: string
```
