### ISSUE TITLE
ui won't acccept definition named 'file'

### ISSUE THREAD

**Issue by Shaun1** [swagger-api/swagger-ui#2093]
I have the following object defined in my swagger.yaml under 'definitions:'

```
  file:
    type: object
    properties:
      filetype:
        type: string
      description:
        type: string
      data:
        type: string
        format: binary
```

The swagger.yaml passes as valid using the editor but the UI hangs in the browser saying:
_Finished Loading Resource Information. Rendering Swagger UI..._

Simply changing the definition name to **file_object** or anything else results in the UI working properly. 

I'm using Python Connexion & It looks like Connexion uses swagger-ui v2.1.4
