### ISSUE TITLE
javascript error when looking for inline model

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#2108]
in 2.1.4, there's a bug loading inline models.  It looks like `this.inlineModels` is unchecked (line 20443) and is causing an issue on referenced schemas.

**Comment by fehguy** [comment]
Looks like the trigger for this is an inline schema in a referenced body parameter.  It can be worked around by using a local reference to the schema:

```yaml
parameters:
  bodyParameterReference:
    name: body
    in: body
    required: true
    schema:
      properties:
        name:
          type: string
```

can be replaced with this:

```yaml
parameters:
  bodyParameterReference:
    name: body
    in: body
    required: true
    schema:
      $ref: '#/definitions/Thingy'
definitions:
  Thingy:
    properties:
      name:
        type: string
```
