### ISSUE TITLE
Inconsistent results when trying to define a multi-select querystring field

### ISSUE THREAD

**Issue by switzer** [swagger-api/swagger-ui#2211]
Hi - I am using Swagger UI v2.10.1 to power my API explorer.  I am having trouble getting expected output.  Here is my field definition YAML:

```
  fields:
    name: fields
    in: query
    description: The data columns to return for the query
    required: false
    type: array
    items:
      type: string
      collectionFormat: csv
      enum:
        - first
        - second
        - third
```

The `collectionFormat` field does not appear to be working.  I am getting inconsistent results in the generated URL when trying out the API.  I either get:

```
field=first&field=second
```

Or I get an array for the field:

```
`field[]=first&field[]=second
```

I would expect the results to be:

```
field=first,second
```
