### ISSUE TITLE
Wrong CURL command for file upload params

### ISSUE THREAD

**Issue by delenius** [swagger-api/swagger-ui#2259]
With a parameter in the swagger spec like

``` yaml
      parameters:
      - name: "file"
        in: "formData"
        description: "csv file"
        required: true
        type: "file"
```

Swagger-UI shows a curl command like

```
curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: text/plain' -F @file.csv  ...
```

This is not correct curl syntax. It should be 

```
curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: text/plain' -F file=@file.csv  ...

i.e. the key (param name) has to be in the form data part.
```
