### ISSUE TITLE
"must be an array" when there is a single item in a `collectionFormat`

### ISSUE THREAD

**Issue by rodoabad** [swagger-api/swagger-ui#2405]
When reporting a bug, please provide the following details:
- swagger-ui version
  2.2.3
- a swagger file reproducing the issue

```
    - name: account
      in: query
      required: false
      description: accounts filter
      type: array
      collectionFormat: "multi"
      items:
        type: string
```

![test](https://cloud.githubusercontent.com/assets/1240667/18568829/b52f89d8-7b64-11e6-8c64-ff72f14ea782.gif)
