### ISSUE TITLE
Authorize: Markdown not being translated

### ISSUE THREAD

**Issue by hpcergar** [swagger-api/swagger-ui#2447]
Hi there,

Just pointing out that when using "Authorize" button or the "!" buttons to enable available authorizations, security definitions containing any markdown are currently being displayed as plain text.

For example, any definition as the following one:

```

securityDefinitions:
  ClientCredentials:
    type: basic
    description: Application **Client key** & **Client secret**  

```

would display **Client key** & **Client secret** (with the asterisks) on authorization popups in swagger-ui, at least in 2.2.4 version.

Thanks for your great job, by the way!
