### ISSUE TITLE
Duplicate schemas needed for simple POST operation

### ISSUE THREAD

**Issue by poisa** [swagger-api/swagger-ui#2455]
I have this object:

```yaml
  Tag:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
        description: Tag name.
      alternate:
        type: string
        description: List of alternate tag spellings.
```

When I reference it in responses it works out fine but when I reference in POST operations so that people know what object to post in the request's body (to create a new object) I don't want it to have a `tag_id` property since it is not required to create the object. In fact it's wrong to pass it as the database will create it for you. 

Is there a way that I can re-use this schema but strip the id? Or do I just have to create a `NewTag` schema without the id property and configure that as the post body? The latte seems awfully redundant, especially for a big api which is what I'm working on documenting.
