### ISSUE TITLE
OAuth2 request adds `vendorExtension` scope to all auth requests

### ISSUE THREAD

**Issue by janslow** [swagger-api/swagger-ui#2483]
When I try to obtain an OAuth2 token using Swagger UI, it displays a `vendorExtensions` scope in the list of scopes for that definition. It also then adds it to the list of scopes in the request from the OAuth server (which causes the request to be rejected).

For example, using the following security definition produces this URL, even if only the `my-scope` scope is selected:

```
http://nimbus.corefiling.com/oauth/authorize?response_type=token&redirect_uri=X&realm=X&client_id=X…ent_id=nimbus-dev&scope=my-scope%20vendorExtensions&state=X
```

```
securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://my-oauth2-server/oauth/authorize
    scopes:
      my-scope: A Scope
```

I believe this is related to https://github.com/swagger-api/swagger-js/pull/869, which added a `vendorExtensions` object to the scopes object.
