### ISSUE TITLE
Array[undefined] in response models

### ISSUE THREAD

**Issue by matteo-mosca** [swagger-api/swagger-ui#2510]
I am using SwaggerUI version 2.2.6

The problem is as follows:

![image](https://cloud.githubusercontent.com/assets/11195767/20480054/2da1ee28-afe1-11e6-97bb-feacb00b1e20.png)

I cannot provide the full swagger document (as it contains sensitive information) but I can provide the relevant portions.

This is the object definition that will be used as items in the array:

```yaml
  ValidationError:
    type: object
    description: Contains a validation error
    properties:
      propertyName:
        type: string
        description: The name of the property that failed validation
      errorMessage:
        type: string
        description: The error message
      attemptedValue:
        type: string
        description: The stringified value that caused the validation error`
```

This is how it is used, in the responses block:

```yaml
  409:
    description: Validation failed
    schema:
      type: array
      description: The validation errors that occurred
      items:
        $ref: "#/definitions/ValidationError"`
```

Please note that the whole swagger document validates successfully, and in the editor I can see the array in the correct way:

![image](https://cloud.githubusercontent.com/assets/11195767/20480110/7c92a824-afe1-11e6-90e8-4abbc4f9f9a0.png)

Thanks.
