### ISSUE TITLE
$ref external yaml file does not work

### ISSUE THREAD

**Issue by zcb22000** [swagger-api/swagger-ui#2694]
When reporting a bug, please provide the following details:
- swagger-ui master version
- a swagger file reproducing the issue
I use the dist folder files in master, and use $ref to reference external yaml file, but it can't resolved.
my yaml format is :
```yaml
  parameters:
    -
      name: request
      in: body
      required: true
      schema:
        $ref: './deviceManageDF.yaml#/definitions/AddDeviceDTONA2Cloud'
```
even modified with full acess path as:
```yaml
  parameters:
    -
      name: request
      in: body
      required: true
      schema:
        $ref: 'http://localhost:8080/swagger-ui/deviceManageDF.yaml#/definitions/AddDeviceDTONA2Cloud'
```
It displayed:
http://localhost:8080/swagger-ui/deviceManageDF.yaml#/definitions/AddDeviceDTOCloud2NA is not defined!
