### ISSUE TITLE
Could not resolve reference when $ref relative path files. "basePath" undefined.

### ISSUE THREAD

**Issue by imallan** [swagger-api/swagger-ui#2746]
After upgrading to v3, the relative path references are not working:
e.g.
```yaml
#...
paths:
  /index:
    $ref: "./paths/index.yaml#/index"
```

will result in:
`Could not resolve reference because of: Tried to resolve a relative URL, without having a basePath. path: 'paths/index.yaml' basePath: 'undefined'`
