### ISSUE TITLE
Handle parameters in the authorization Url

### ISSUE THREAD

**Issue by B-Prod** [swagger-api/swagger-ui#2837]
Using access code, I wonder how to handle parameters in the authorization URL like:
https://developers.wrike.com/documentation/oauth2

We are supposed to specify the Client ID but I didn't find a way to properly handle that with Swagger:
* https://www.wrike.com/oauth2/authorize?client_id=<client_id>&response_type=code

Moreover, the Client ID should also be used when getting the token and that is also not covered:
```
POST https://www.wrike.com/oauth2/token
//Parameters:
client_id=<client_id>
client_secret=<client_secret>
grant_type=authorization_code
code=<authorization_code>
```

What would be the best way to handle this?

For info, below is the current (not-working) definition:
```
securityDefinitions:
  oauth:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://www.wrike.com/oauth2/authorize?client_id={client_id}&response_type=code
    tokenUrl: https://www.wrike.com/oauth2/token
```

**Comment by bodnia** [comment]
@B-Prod for oauth2 authorization `scopes` field is required please see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-15

Also oauth2 works only with running server as there must be a page where to redirect after authorized and defined `oauth2RedirectUrl` in constructor:
```
window.onload = function() {
  const ui = SwaggerUIBundle({
    url: "http://petstore.swagger.io/v2/swagger.json",
    dom_id: "#swagger-ui",
    oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html",
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })

  window.ui = ui
}
```
In the example above I added redirect page for dev server, it can be found here `swagger-ui/public/oauth2-redirect.html`.

The correct definition would be:
```
securityDefinitions:
  oauth:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://www.wrike.com/oauth2/authorize
    tokenUrl: https://www.wrike.com/oauth2/token
    scopes:
      write:auth: modify auth in your account
      read:auth: read your auth
```

Then to add `client_id` you should enter it to the field:
<img width="659" alt="screen shot 2017-04-05 at 4 33 36 pm" src="https://cloud.githubusercontent.com/assets/8950657/24707802/a5e9c418-1a1d-11e7-89c3-49d70bb97524.png">
Also `client_secret` may be filled.

When you click on `Authorize` button, you'll be redirected to `https://www.wrike.com/oauth2/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3200%2Foauth2-redirect.html&scope=[chosen scopes]&state=oauth&client_id=[entered client_id]`

Then the authorization server should redirect to passed redirect page and add query parameter `code` with authorization code. After this, the next pure POST request to tokenUrl `https://www.wrike.com/oauth2/token` with following fields:
```
  "code": [code from previous request], 
  "redirect_uri": [stays the same as for previous request],
  "grant_type": "authorization_code",
  "client_secret": [client_secret filled before clicking on authorize],
  "client_id": [client_id filled before clicking on authorize]
```
It's expected to redirect to `redirect_uri` and put `token` as a query parameter, if it's successful - the token is set to SwaggerUI.

Hope this helps. In case of any questions please leave them here and I'll be happy to help.
