### ISSUE TITLE
Is ordered-pair (coordinates) not supported in Swagger-UI?

### ISSUE THREAD

**Issue by akeshwarj** [swagger-api/swagger-ui#2939]
I searched, but couldn't find. Is this feature not supported? Here's what I have in the Editor:

```
location_array:
        type: array
        minItems: 2
        items:
          $ref: '#/definitions/Point2D'
```

```
Point2D:
    description: contains the 2D coordinates of a point. The format is (longitude, latitude)
    type: array
    maxItems: 2
    minItems: 2
    items:
      type: number
      example: 12.34
```

The rendered UI is:
```
"location_array": [
    [
      12.34
    ]
  ],
```

I'm trying for the UI:
```
"location_array": [
    [
      12.34, 12.34
    ]
  ],
```

I checked out other issues and found that minItems is not supported in the UI. Is there a way to do it other than using an array?
