### ISSUE TITLE
Title not displayed for non-object models

### ISSUE THREAD

**Issue by lekoder** [swagger-api/swagger-ui#2947]
Models that are not objects (scalars, arrays) have title missing.

## Definition:
```
definitions:
  Scalar:
    type: string
  Array:
    type: array
    items:
      type: string
```
## Expected result:
```
Scalar ⇄ Scalar string
Array  ⇄ Array[string]
```
## Actual result:
```
string
[...]
```
[Ghist demostrating issue](https://gist.githubusercontent.com/lekoder/c03a0751609829888451909539f315be/raw/0be8864b836ae2aaaed18c01c3995bbfc0c5cbff/swagger-ui-scalar-title-missing.yaml)

Affected version: **v3.0.0-229-g7790383**
