### ISSUE TITLE
macro features lost in 3.x rewrite

### ISSUE THREAD

**Issue by fehguy** [swagger-api/swagger-ui#3067]
During the 3.x rewrite, the macro features (`modelPropertyMacro`, `parameterMacro`) were accidentally dropped.  The goal of those functions was to "do something" after reading & resolving a specification, by allowing client-side code to update model properties and parameters.

For example, say you have a model like this:

```
type: object
properties:
  userId:
    type: string
    example: anonymous
```

a `modelPropertyMacro` would allow code to be executed in a fashion like this:

```js
function (operation, parameter) {
/** mutate the parameter here, the `operation` is passed for context **/
  if(parameter.userId) {
    parameter.userId.example = 'Tony'
  }
}
```

This would create the _effective_ model:

```
type: object
properties:
  userId:
    type: string
    example: Tony
```

And the UI could use that value for default values when posting data, etc.
