### ISSUE TITLE
Basic Auth issue

### ISSUE THREAD

**Issue by FerrariAlberto** [swagger-api/swagger-ui#3069]
hello everyone,

i just added basic authentication in my swagger spec like this

```
securityDefinitions:
  Login:
    type: basic
...

/restful/export/api/products.xml:
    get:
      tags:
        - Catalog
      produces:
        - application/xml
      security:
        - Login: []
      description:
   ...
```

but when i try the method out in swagger ui im getting 401 back.

![screenshot 28](https://cloud.githubusercontent.com/assets/25078470/25939823/6b254dc4-3634-11e7-942c-70446d0a847e.png)

i've read that some people edit the index.html to make it work but i'm not sure how to do it.
i'm using swagger-ui 3.0.3 and the allow-control-allow-origin chrome extension
