### ISSUE TITLE
Can I mark a sub-object as required?

### ISSUE THREAD

**Issue by trip-somers** [swagger-api/swagger-ui#3100]
VERSION: swagger-api/swagger-ui v3.0.10

```
definitions:
  Car:
    type: object
    properties:
      engine_size:
        type: string
        example: 5.3L
      driver:
        type: object
        properties:
          name:
            type: string
            example: Guy B. Driver
    required: [engine_size, driver]
```

The above YAML successfully marks `engine_size` as required but does not mark the driver object as required. See image below:

![screen shot 2017-05-17 at 4 54 49 pm](https://cloud.githubusercontent.com/assets/4362516/26177991/ad602eba-3b21-11e7-873a-170f3d0607ed.png)

Am I describing the requirement or model incorrectly, or is this an actual issue?

EDIT: I'm using swagger-ui-bundle.js and swagger-ui-standalone-preset.js from the /dist folder of the v3.0.10 release.
