### ISSUE TITLE
Example and additionalProperties

### ISSUE THREAD

**Issue by OverlyExcessive** [swagger-api/swagger-ui#3111]
The example rendered by Swagger UI for a schema such as:

```yaml
  SomeDefinition:
    type: object
    properties:
      foo:
        type: string
        example: bar
      extras:
        type: object
        additionalProperties:
          type: string
          example:
            extra: foobar
```

Will generate an example response as such:

```json
{
  "foo": "bar",
   "extras": {
     "additionalProp1": {
       "extra": "foobar"
     },
     "additionalProp2": {
       "extra": "foobar"
     },
     "additionalProp3": {
       "extra": "foobar"
     }
   }
}
```

Quite confusing for the consumer of the API as this is not a response that conforms to the schema.

**Comment by webron** [comment]
How does that not conform to the schema?

**Comment by hkosova** [comment]
@OverlyExcessive, in your spec `additionalProperties` are defined as `type: string` but have an object example - `extra: foobar`, so the UI renders those additional properties as objects. I guess what you are looking for is

```
      extras:
        type: object
        additionalProperties:
          type: string
          example: foobar
```
or
```
      extras:
        type: object
        additionalProperties:
          type: string
        example:   # Note the "example" is on the object level, not under additionalProperties
          extra: foobar
```
