### ISSUE TITLE
Use more specific name for CSS pulse animation

### ISSUE THREAD

**Issue by scottohara** [swagger-api/swagger-ui#3169]
In `style/_buttons.scss`, there is an animation called `pulse` defined:

```css
  &.execute
  {
    animation: pulse 2s infinite;
     ...
  }
}

@keyframes pulse
{
  0%
  {
    ... 
  }
  70%
  {
    ...
  }
  100%
  {
    ...
  }
}
```

`pulse` is a very generic name, and it is not uncommon for other CSS libraries to define their own version of a `pulse` animation.

When Swagger UI is embedded into a site that has it's own definition of a `pulse` animation, it can interfere or override the one defined here.

I would suggest using a less generic name for animations to avoid possible conflicts, such as:

 ```css
@keyframes swagger-ui-pulse { ... }
```

(I would be happy to submit a PR to this effect if this is considered a good idea).
