### ISSUE TITLE
Swagger-ui oauth2 accesscode flow not working correctly

### ISSUE THREAD

**Issue by chanurahemal** [swagger-api/swagger-ui#3172]
Hi All,

I started using swagger-ui to use with oauth2 access code flow with interactive facility( Try it out feature)
I downloaded latest master version and copied 'dist' folder and run 'live-server' by mounting to dist folder.It loads my test.yaml file and "Authorize"  also will be appeared(But it is showing unlock icon though). Refer unlock-icon.png

Anyway once i click Authorize button, it shows the popup and i can enter client id and secret too. Refer authorize-popup.png

Then once i click Authorize button with correct client id and secret it will open a new window and i can see the generated code with the redirect url. But problem is, it won't close that window and it remain in the same page. That new window url something like this
http://localhost:3200/oauth2-redirect.html?code=fs-QFeYgj-bpXLjs8Fbak2pm2DwZZs0hc4QU0gKV&state=RnJpIEp1biAwMiAyMDE3IDExOjU4OjQ2IEdNVCsxMDAwIChBRVNUKQ%3D%3D

Can you just explain is this something on my code or defect? i spend more than 3 days to fix this issue with several tricks, but didn't success.

My security definitions on the yaml file looks like follow
```yaml
securityDefinitions:
  OauthSecurity:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://xxxxxx.xxxxx.xxxx/as/authorization.oauth2
    tokenUrl: https://yyyyy.yyyyy.yyyyy/as/token.oauth2
    grantType: authorization_code
    scopes:
      admin: Admin things

security:
 - OauthSecurity:
    - admin
```
Thank you very much for your help. Really looking forward for a quick reply :)
![authorize-popup](https://cloud.githubusercontent.com/assets/11264518/26713925/4dc7c07e-47b2-11e7-997d-68117665d911.png)
![unlock-icon](https://cloud.githubusercontent.com/assets/11264518/26713926/4dc99188-47b2-11e7-994e-8c8720cc3deb.png)
