### ISSUE TITLE
how to set the default value for the array?

### ISSUE THREAD

**Issue by codepandy** [swagger-api/swagger-ui#3202]
- swagger-ui version 2.0
the below is the part code:
```
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: "array"
          items:
            type: "string"
          default:
          - "aaaaa"
          - "bbbbb"
```
the code is invalid.

**Comment by webron** [comment]
There's no swagger-ui version 2.0. Please provide the correct version.

**Comment by codepandy** [comment]
@webron I use the editor is http://editor.swagger.io/#/

**Comment by webron** [comment]
This seems like a bug then.

**Comment by codepandy** [comment]
how to solve the problem?
the below code only can show the first value,but can't show multiple value.
```
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: "array"
          items:
            type: "string"
            enum:
            - "aaaaa"
            - "bbbbb"
            - "ccccc"
```

**Comment by webron** [comment]
It's a bug, no workaround.

**Comment by hkosova** [comment]
@codepandy, if you need an example _for display purposes_, you can use `example`:
```
        schema:
          type: array
          items:
            type: string
          default:
          - aaaaa
          - bbbbb
          example:
          - aaaaa
          - bbbbb
```
