### ISSUE TITLE
how to set the different parameter to a url?

### ISSUE THREAD

**Issue by codepandy** [swagger-api/swagger-ui#3214]
- swagger-ui version the latest
the below url is a example:
```
  /store/order?name=abe
  /store/order?Id=12
```
the two urls' http type are get.
the two parameters can't be used together.

**Comment by webron** [comment]
The spec doesn't allow you to define mutually exclusive parameters. You'd have to define them both and add documentation to that effect.

**Comment by codepandy** [comment]
@webron 
If I define them both,there will be a error.
```
duplicated mapping key.
```

**Comment by webron** [comment]
The spec doesn't allow you to define query parameters as part of the path.

**Comment by hkosova** [comment]
@codepandy: what @webron is trying to say is that you need a single path with both parameters:
```
paths:
  /store/order:
    description: The `name` and `Id` parameters are mutually exclusive.
    parameters:
      - in: query
        name: name
        type: string
      - in: query
        name: Id
        type: integer
```
There's a proposal to add support for parameter dependencies in the OpenAPI Specification in OAI/OpenAPI-Specification/issues/256, you can follow that for updates.
