### ISSUE TITLE
How to define some global parameters?

### ISSUE THREAD

**Issue by codepandy** [swagger-api/swagger-ui#3232]
- swagger-ui the latest
Because every url has some same parameters, I want to define them as global parameter.

the below is my code:
```
host: "110.178.147.82:8000"
basePath: "/"
parameters:
 sid:
  name: "sid"
  in: "header"
  required: false
  type: "string"
```
but the url can't show the parameter.
