### ISSUE TITLE
Supplying a malformed JSON payload correctly returns a "SyntaxError: Unexpected token" but it is returned as a 200 status code.

### ISSUE THREAD

**Issue by chevex** [swagger-api/swagger-ui#3262]
Swagger-ui version: 2.2.8

```
  /reports/generate/{templateName}:
    post:
      summary: Combine provided data with the specified markup template to generate a complete report and optionally create and store as a PDF attachment in Salesforce.
      description: Generates a complete report using the specified template and returns the completed markup. Will also create and store PDF attachment in Salesforce if employeeId and sfId (CAD SF ID) are specified.
      parameters:
        - name: templateName
          in: path
          description: The name of the desired template.
          required: true
          type: string
        - name: data
          in: body
          description: The data payload required to generate a report using the desired template.
          required: true
          schema:
            type: object
            properties:
              employeeId:
                type: string
              sfId:
                type: string
              reportName:
                type: string
              reportData:
                type: object
```

If you supply a random string for the body (`data`) the response body correctly contains the parsing error `SyntaxError: Unexpected token` but the status code is 200.

![image](https://user-images.githubusercontent.com/874394/27309878-bbfe49aa-5513-11e7-9ecb-f51f3f155f7c.png)

Similarly, if you supply an empty JSON payload it correctly says `ValidationError: "data" is required` but again the response code is 200.

![image](https://user-images.githubusercontent.com/874394/27309937-0583f5d4-5514-11e7-937d-1f7c84d3260d.png)
