### ISSUE TITLE
Required body parameters are not marked as such

### ISSUE THREAD

**Issue by rjakes** [swagger-api/swagger-ui#3330]
Swagger UI 2.2.8

It looks like Swagger UI 2.2.8 doesn't mark body parameters as required, though Swagger Editor does. Apologies if it's been logged, I can't seem to fund much on it.

Roger

![screen shot 2017-07-03 at 12 21 57 pm](https://user-images.githubusercontent.com/2447356/27807572-8a5169da-5ff6-11e7-9020-2262fd728cbc.png)

![screen shot 2017-07-03 at 12 21 40 pm](https://user-images.githubusercontent.com/2447356/27807575-8f917b38-5ff6-11e7-9bdd-489b1883152b.png)

![screen shot 2017-07-03 at 2 14 49 pm](https://user-images.githubusercontent.com/2447356/27808054-0c7d51aa-5ffa-11e7-938c-8d9bd5f26fcd.png)

```
  '/items/{idItem}':
    post:
      summary: Insert an item
      parameters:
        - $ref: '#/parameters/IdItemInPath'
        - in: body
          name: body
          description: Post item payload
          required: true
          schema:
            $ref: "#/definitions/ItemPost"
```

```
definitions:
  ItemPost:
    required:
      - idShot
      - styleGroupNumber
      - colorCode
    properties:
      idShot:
        type: integer
        format: int32
      brand:
        type: string
        description: length limited to 255 chars
      color:
        type: string
        description: length limited to 255 chars
      colorCode:
        type: string
        description: length limited to 255 chars
      departmentNumber:
        type: string
        description: length limited to 255 chars
      description:
        type: string
        description: text column, allows for 21,844 chars
      liveDate:
        type: string
        format: date
        description: YYYY-DD-MM
      price:
        type: number
        format: float
      styleGroupNumber:
        type: string
      vpn:
        type: string
        description: vendor product number. length limited to 255 chars
```
