### ISSUE TITLE
Authentication headers are not sent on execute

### ISSUE THREAD

**Issue by juliusza** [swagger-api/swagger-ui#3386]
What am I doing wrong?? Header is not set on basic authorization:

```yaml
securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
```

No header is set on execute requests (I can see this in chrome dev tools). No, it's not CORS. Worked just fine with version 2.x.x

Even the provided curl command does not have header set:
```curl -X GET "https://192.168.52.21/pub/v1/sites" -H "accept: application/json"```

And, yes, I have authenticated using "Authorize" popup

Version 3.0.18

**Comment by hkosova** [comment]
Does your spec use `security` to actually apply the security scheme to operations?
```
security:
- api_key: []

# or
paths:
  /something:
    get:
      security:
        - api_key: []
      ...
```
