### ISSUE TITLE
Multiline description in schema

### ISSUE THREAD

**Issue by SORC3r3r** [swagger-api/swagger-ui#3395]
Hi,

while describing the attributes in my schema objects, sometimes the description is pretty long and it would be nice to split it into multiple lines.

I tried:
```
attribute_one: 
          type: "string"
          minLength: 1
          enum:
            - "red"
            - "blue"
            - "green"
          required: true
          description: |
            "red" stands for red 

            "blue" stands for blue 

            "green" stands for green 
```
I was expecting it to be like this:

"red" stands for red
"blue" stands for blue
"green" stands for green

Instead I got this:

"red" stands for red "blue" stands for blue "green" stands for green

First I tried to use a table, but that didn´t work either.
