### ISSUE TITLE
Same parameter as a query and a formData parameter doesn't appear as a formData parameter

### ISSUE THREAD

**Issue by conorlennon** [swagger-api/swagger-ui#3511]
swagger-ui version v3.1.2 (and earlier)

File reproducing this issue:
[yaml_test.txt](https://github.com/swagger-api/swagger-ui/files/1193546/yaml_test.txt)

In the attached yaml, authorised is a patch parameter in query and separately in formData.
In the v2 swagger editor, authorised is available as a query parameter and also as a formData parameter - as I would expect.
However with the same yaml, in the swagger v3 editor, authorised is only available as a query parameter.

**Comment by skubot** [comment]
also same parameter name in path and in query do not show both.
In the following example only the path parameter is shown.
eg:
```
  parameters:
    - name: org_user_id
      in: path
      required: true
      type: string
    - name: org_user_id
      in: query
      type: string
```
