### ISSUE TITLE
POST formData not working on http://editor.swagger.io/

### ISSUE THREAD

**Issue by dannoehe** [swagger-api/swagger-ui#3629]
I am trying http://editor.swagger.io/ to edit API doc, "formData" can be used to indicate the input parameter as form data and I assume such parameter can be parsed on server side to get its name and value, but actually server hangs and timeouts.

Example:
- client side:
```yaml
'/Buckets/{bucket}/upload':
    post:
      parameters:
        - in: path
          name: bucket
          description: Name of bucket where the file is uploaded
          required: true
          type: string
        - in: formData
          name: name
          description: file name to upload
          required: false
          type: string
```
- on right side of UI on http://editor.swagger.io/, I can see the request is translated to curl command like below, 
`curl -X POST "http://127.0.0.1:3002/api/v1/Buckets/bucket-test/upload" -H  "accept: application/json" -H  "content-type: application/x-www-form-urlencoded" -d "name=testFileName"`
- I think the right curl command for it should change "-d" as "-F", like this which I verified correct.
`curl -X POST "http://127.0.0.1:3002/api/v1/Buckets/bucket-test/upload" -H  "accept: application/json" -H  "content-type: application/x-www-form-urlencoded" -F "name=testFileName"`
- on server side, it hangs to parse request body, timeouts and returns error "Error: Request aborted"

This issue seems like https://github.com/swagger-api/swagger-ui/issues/838 which was resolved in 2015, but is the fix missed on this online tool? If not same one, could you please help on this? Thanks!
