### ISSUE TITLE
CommonMark rendering failed with description on global tags object

### ISSUE THREAD

**Issue by anthcha** [swagger-api/swagger-ui#3636]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | OpenAPI 3.0
| Which Swagger-UI version?       |  Current release on http://editor.swagger.io/
| How did you install Swagger-UI? | http://editor.swagger.io/
| Which browser & version?        |  Chrome last release
| Which operating system?         |  Windows 10

### Demonstration API definition
```yaml
tags:
  - name: pets
    description: |
      __Everything about your Pets__
    externalDocs:
      url: http://docs.my-api.com/pet-operations.htm
```

### Current Behavior
It's seem the CommonMark syntax is not interpreted in this context (but seems to be valid when I read the spec : https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#tagObject) 

### Context
Our need is to add a common description un rich text format for eact tag. In fact it would be very nice to be able to click on the tag to display then the full description and the different operation tagged.
