### ISSUE TITLE
enum values are not displayed in example/model view

### ISSUE THREAD

**Issue by jcferrer** [swagger-api/swagger-ui#3758]
Using this definition as an example:

```
accessTokenReq:
    type: object
    properties:
      grant_type:
        enum:
          - client_credentials
          - authorization_code
          - implicit_grant
          - password
      client_id:
        type: string
      client_secret:
        type: string
```

Rendered by UI:

Example
```
{
  "client_id": "string",
  "client_secret": "string"
}
```

Model

```
accessTokenReq {
  grant_type {
  }
  client_id | string
  client_secret | string
}
```
