### ISSUE TITLE
enum values not displayed in example/model view (resubmitted using template)

### ISSUE THREAD

**Issue by jcferrer** [swagger-api/swagger-ui#3761]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         | Bug  
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.3.1
| How did you install Swagger-UI? | embedded in swagger-tools module
| Which browser & version?        | Safari Version 11.0 (12604.1.38.1.7)
| Which operating system?         | macOS Sierra Version 10.12.6 (16G29)

### Demonstration API definition

```yaml
accessTokenReq:
    type: object
    properties:
      grant_type:
        enum:
          - client_credentials
      client_id:
        type: string
      client_secret:
        type: string

```
### Expected Behavior

Example section:
```
{
  "grant_type": "client_credentials",
  "client_id": "string",
  "client_secret": "string"
}
```
Model section
```
accessTokenReq { 
  grant_type  = ['client_credentials'],
  client_id | string
  client_secret | string
}
```
### Current Behavior

Rendered by UI:

Example section:
```
{
  "client_id": "string",
  "client_secret": "string"
}
```
Model section
```
accessTokenReq {
  grant_type {
  }
  client_id | string
  client_secret | string
}
```

**Comment by webron** [comment]
While this _is_ a bug, you can easily overcome it by explicitly adding the type.

```yaml
  accessTokenReq:
    type: object
    properties:
      grant_type:
        type: string
        enum:
          - client_credentials
      client_id:
        type: string
      client_secret:
        type: string
```
