### ISSUE TITLE
Wrong font color for description in the responses block

### ISSUE THREAD

**Issue by haqqi** [swagger-api/swagger-ui#3783]
In swagger 3.3.2, using openapi 3.0.0, the description in the response list cannot be read. I suppose it is because of wrong font color.

Note: Using dist folder version of the release.

![image](https://user-images.githubusercontent.com/831763/31761455-22165e34-b4e2-11e7-8a19-5cbc39109165.png)

**Comment by wiesson** [comment]
I can confirm the error. 

Wanted color:
```css
.swagger-ui .response-col_description__inner div.renderedMarkdown {
    color: #fff;
}
```    
but got overridden by:
```css
.swagger-ui .renderedMarkdown p {
    color: #3b4151;
    ...
}
```
