### ISSUE TITLE
Array items with oneOf schemas are rendered as null in examples

### ISSUE THREAD

**Issue by hkosova** [swagger-api/swagger-ui#3859]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 3.0
| Which Swagger-UI version?       | 3.4.2
| How did you install Swagger-UI? | http://editor.swagger.io
| Which browser & version?        | Chrome 62
| Which operating system?         | Windows 7

### Demonstration API definition
```yaml
openapi: 3.0.0
info:
  version: 0.0.0
  title: test

paths:
  /:
    get:
      responses:
        '200':
          description: An array containing strings and/or integers
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - type: string
                    - type: integer
```

### Expected Behavior
The rendered array example should use the appropriate item type - in this example, string and/or integer, that is, something like
```yaml
[
  "string"
]
```
or
```yaml
[
  0
]
```
or maybe even
```yaml
[
  "string",
  0
]
```

### Current Behavior
The response example is displayed as
```yaml
[
  null
]
```
which is wrong - because the array item schema is not nullable.

### Context
This might be related to #3803.

### Workaround
Add an `example` to the schema:
```yaml
              schema:
                type: array
                items:
                  oneOf:
                    - type: string
                    - type: integer
                  example: apples
                # OR
                example:
                  - oranges
                  - 15
```
