### ISSUE TITLE
securityDefinitions defined names are not used in Authorization dialog anymore

### ISSUE THREAD

**Issue by grigoni** [swagger-api/swagger-ui#3907]
issue found on v3.4.3 and 3.4.4 but worked on v3.3.1

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | v2.0
| Which Swagger-UI version?       | v3.4.3 and 3.4.4
| How did you install Swagger-UI? | direct via nginix
| Which browser & version?        | firefox
| Which operating system?         | windows 7

### Demonstration API definition
```yaml
securityDefinitions:
  FD_REMOTE_USER_DEF:
    type: "apiKey"
    name: "FD_REMOTE_USER"
    in: header
  FD_GIVEN_TID_DEF:
    type: "apiKey"
    name: "FD_GIVEN_TID"
    in: header
  FD_TID_DEF:
    type: "apiKey"
    name: "FD_TID"
    in: query
security:
  - FD_REMOTE_USER_DEF: []
    FD_GIVEN_TID_DEF: []
    FD_TID_DEF: [] 
```
### Configuration (browser query string, constructor, config.yaml)
on first call, open Auth modal windows and fill data

### Expected Behavior
the value in the name attribute must be shown as it worked in v3.3.1
the corresponding headers/query params are nonethless sent but customers are disoriented by definition prop name

### Current Behavior
 now it only shows the type definition prop name (like FD_REMOTE_USER_DEF:)

### Context
trying to send additional headers in a multi proxies env
