### ISSUE TITLE
Having a nested object structure in formData and get the same reflected on swagger-ui

### ISSUE THREAD

**Issue by cskru** [swagger-api/swagger-ui#4041]
Currently, swagger accepts properties in formData directly. What I intend to do is, formData should be able to accept a nested object and the file will be present somewhere inside. (See example below).
I am not sure if this is a bug or a whole new feature to be added.

| Q                               | A
| ------------------------------- | -------
| Which Swagger/OpenAPI version?  | 2.0
| Which browser & version?        | Chrome latest
| Which operating system?         | Windows

```
formData: 
   { file: 
      { opt: 
         { filename: 'abc.json',
           contentType: 'application/octet-stream' 
          },
        value: <The file contents are to be placed here (octet-stream)> 
       } 
   }
```
### Current Behavior

I tried to do the same like:
```yaml
            - name: file
              in: formData
              type: object
              properties:
               file:
                   type: object
                   properties:
                       opt:
                          type: object
                          properties:
                              filename:
                                  type: string
                                  example: "abc.json"
                                  required: true
                              contentType:
                                   type: string
                                   example: 'application/octet-stream' 
                       value:
                            type: file
```
But this doesn't work.
The output is like this:
![image](https://user-images.githubusercontent.com/22630066/34142432-108fbfde-e4ad-11e7-9c31-9a9cd029e0c0.png)

I want to represent formData as a nested object itself and represent it in swagger appropriately.
Is there a way to do so?

Thanks in advance!
