### ISSUE TITLE
Definitions references from external yaml files do not work

### ISSUE THREAD

**Issue by svetvasilev** [swagger-api/swagger-ui#4070]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | 3.8.1 (Latest stable)
| How did you install Swagger-UI? | download from repo/dist
| Which browser & version?        | Chrome v63.0.3239.84
| Which operating system?         | Win Server 2008 R2

### Demonstration API definition

```yaml
  ExampleResponse:
    type: "object"
    properties:
      StatusHeader:
        $ref: "#/definitions/StatusHeader"
      ResponseBody:
        $ref: "externaldefs.yaml#/Profile"
```
The referenced type Profile in the external file ecternaldefs.yaml is defined as follows:

```yaml
Profile:
  type: "object"
  required:
    - "ProfileKey"
    - "ProfileId"   
  properties:
    ProfileKey:
      type: "string"
    ProfileId:
      type: "string"
    PersonalInfo:
      type: "object"
      properties:
        FirstName:
         type: "string"
        LastName:
         type: "string"
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
  "it": { "is defined": "as per the default description in the documentation with changed URLto the yaml spec file" }
}
```

`?yourQueryStringConfig=here`

### Expected Behavior

The request and response objects that are referenced through external files should be correctly rendered in the UI. 
### Current Behavior

Instead an error for each undersolved reference is displayed: 
  Could not resolve reference because of: Not Accepted.
### Possible Solution

Investigated in browser tools and found out that the UI was successfully attempting to download the referenced external files. However it was getting a 406 Not Accepted response from the server. Upon closer inspection it turned out that the Accept header for these requests was just set to application/json. It should have text/yaml, application/yaml MIME types as well, at least.

I quick fixed this locally by doing a search and replace in the swagger-ui-bundle.js file of where Accept header is defined. Found 3 places out of which two had only the value of "application/json". Appended to both the value "text/yaml" (as this is how yaml static content MIME type is registered on my dev box) and now it works flawlessly.

### Context

Tried to split a very big yaml file into smaller, more manageble files in order to impose some reusability of the type definitions.
