### ISSUE TITLE
Docker container can't run twice when BASE_URL is defined

### ISSUE THREAD

**Issue by champjss** [swagger-api/swagger-ui#4072]
Docker container can't run twice because of trying to move the moved file in docker-run.sh.

If you're trying to use swagger-ui in Docker Compose, we may use this as docker-compose.yml

```yml
version: "3.3"

services:
  api-reference:
    image: swaggerapi/swagger-ui:v3.8.0
    environment:
      - BASE_URL=/docs/api
```

However, if BASE_URL is defined, it will try to move files with `mv ${NGINX_ROOT}/*.* ${NGINX_WITH_BASE_URL}/`, that works with the first run of `docker-compose up`, but just the first one. This command will failed for later `docker-compose up` with this error:

```
mv: can't rename '/usr/share/nginx/html/*.*': No such file or directory
```
