### ISSUE TITLE
Support "x-tokenName" as in swagger-ui 2 for choosing another OAuth2.0 token field

### ISSUE THREAD

**Issue by thjaeckle** [swagger-api/swagger-ui#4084]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Feature request
| Which Swagger/OpenAPI version?  | OpenAPI 2.0
| Which Swagger-UI version?       | Swagger 3.9.0
| How did you install Swagger-UI? | Official Docker image
| Which browser & version?        | Latest Chrome
| Which operating system?         | Win

Swagger-UI 2 supported reading a "x-tokenName" property from a "oauth2" entry in "securityDefinitions", see also PR #2587
That was used in order to select another JSON field (other to "access_token") in the token response from a OAuth2.0 server.

For example Google OAuth2.0 sends back a token in form:
```json
{
 "access_token": "....",
 "token_type": "Bearer",
 "expires_in": 3599,
 "id_token": "...."
}
```

Swagger-UI 3.9.0 can only send the "access_token" to the backend for "try out".
In Swagger-UI 2 one could choose to use the "id_token" instead.

### Demonstration API definition

```yaml
securityDefinitions:
  Google:
    type: oauth2
    description: Use "OAuth2.0" with your Google-ID.
    authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
    tokenUrl: https://www.googleapis.com/oauth2/v4/token
    x-tokenName: id_token
    flow: accessCode
    scopes:
      openid: Access your Google-ID
```

### Expected Behavior
The previously supported `x-tokenName` can be used in order to select another field from the token JSON as bearer token.

### Current Behavior
The `x-tokenName` is ignored.

### Context
Trying to use the "id_token" instead of the "access_token" so that the backend does not need to retrieve the "id_token" again with the "access_token".
