### ISSUE TITLE
Can't resolve paths ref to yaml files

### ISSUE THREAD

**Issue by Frank591** [swagger-api/swagger-ui#4190]
Swagger UI: 3.9.3
i have index.yaml with references to other yaml files from **paths** section

```
...
paths: 
  allOf:
  - $ref: "Test.yaml#/paths"    
```

It's works ok, when i working with that as with local files. But when i trying to hosting swagger ui on IIS, i get next error
Errors
```

Resolver error at paths.$ref
Could not resolve reference because of: Not Acceptable
```

Similiar issue is https://github.com/swagger-api/swagger-ui/issues/4070, but in Swagger UI 3.9.3 it's still not working. Are there any solutions or workarounds for that problem?

PS Sorry for my bad English

**Comment by hkosova** [comment]
This is not a valid definition - `$ref` is not supported directly under `paths`. You can only `$ref` individual paths, like so:

```yaml
paths:
  /foo:
    $ref: foo.yaml
  /bar:
    $ref: bar.yaml
```
