### ISSUE TITLE
JSON-schema combining keywords allowed outside schema objects

### ISSUE THREAD

**Issue by MikeRalphson** [swagger-api/swagger-ui#4362]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  | OAS 3.0.x
| Which Swagger-UI version?       | 3.12.1
| How did you install Swagger-UI? | Hosted by third-party
| Which browser & version?        | Firefox 59
| Which operating system?         | Ubuntu Linux

### Demonstration API definition

* https://ohdearapp.com/swagger.json
* https://ohdearapp.com/swagger#/sites/get_sites

Excerpt:

```yaml
      parameters:
        - allOf:
            - name: filter
              in: query
              description: Filters data exactly
              required: false
              schema:
                type: integer
            - name: 'filter[team_id]'
```

### Expected Behavior

swagger-ui should *probably* draw attention to this in some way (until the validator button is reinstated) to ensure people don't write their OAS documents in this fashion with JSON schema keywords such as `allOf`, `anyOf`, `oneOf` and `not` outside schema objects.

### Current Behavior

The (in this case) parameter is rendered **as if** the syntax was correct OAS 3.0.x

### Possible Solution

Limit JSON schema keyword processing to schema objects.

### Context

Trying to validate a third-party OAS document, which I think suffers from the "it renders ok in swagger-ui so it must be correct" mentality.
