### ISSUE TITLE
Regression: #4162 OAS3.0 parameter validation not working

### ISSUE THREAD

**Issue by pho-enix** [swagger-api/swagger-ui#4374]
OAS3.0 parameters are not validated and do not trigger errors.

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         | Bug 
| Which Swagger/OpenAPI version?  | OAS3.0
| Which Swagger-UI version?       | 3.13.0
| How did you install Swagger-UI? |  npm swagger-ui-dist
| Which browser & version?        | firefox, chrome
| Which operating system?         | linux, windows

### Demonstration API definition

```yaml
    parameters:
    - name: mustbeset
      schema:
        type: string
      in: path
      required: true
```

### Expected Behavior
1) Hit Try it out button
2) Leave the required parameter empty
3) Hit Execute
4) Required parameter gets highlighted red and gives users feedback that it's required

### Current Behavior
Nothing happens in frontend. No user feedback

### Hints
Schema Validation works (at least partial)
Error Feedback in Frontend Validation works (at least partial)
Probably the errors get lost somewhere in redux state
