### ISSUE TITLE
Parser error: Parser error on line 57 end of the stream or a document separator is expected

### ISSUE THREAD

**Issue by maniutek20** [swagger-api/swagger-ui#4428]
When I trying to use (local) swagger.json file I have got a problem with parsing/validating. Its working locally on http://localhost:8080/ but when I try to load the index.html file on browser it shown error: "Parser error: Parser error on line 57 end of the stream or a document separator is expected". I set "validatorUrl: null," in dist/index.html and fix CORS but problem is still exists. What is a problem here? Is there any configuration tips? It looks like Dist bug

| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  |V/3.13.3 (#4420)
| Which Swagger-UI version?       |	
| How did you install Swagger-UI? | Github download
| Which browser & version?        |Chrome
| Which operating system?         | Win10

### Demonstration API definition - full swagger.json file

```yaml
{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "tytul",
    "contact": {
      "name": "mario",
      "email": "a@b.com"
    }
  },
  "host": "127.0.0.1:8080",
  "basePath": "/datasnap/rest/TServerMethods1/",
  "schemes": [
    "http"
  ],
  "paths": {
    "/test": {
      "get": {
        "description": "Main Desc",
        "parameters": [
          {
            "in": "query",
            "name": "some name",
            "description": "desc",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "some desc"
          }
        }
      }
    }
  }
}
```

### Configuration (dist/swagger.json)

```js
{
  window.onload = function() {
  
  // Build a system 
  const ui = SwaggerUIBundle({
    url: "./swagger.json",
    dom_id: '#swagger-ui',
    deepLinking: true,
	validatorUrl: null,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: "StandaloneLayout"
  })
  window.ui = ui
}
}
```
