### ISSUE TITLE
Unknown Security Definition for HTTP Bearer authorization 

### ISSUE THREAD

**Issue by fzlrhmn** [swagger-api/swagger-ui#4481]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  bug
| Which Swagger/OpenAPI version?  | 3.0
| Which Swagger-UI version?       | 3.13.6
| How did you install Swagger-UI? | `yarn` or `npm`
| Which browser & version?        | chrome 66.0.3359.117
| Which operating system?         | Mac OSX 10.13.2

### Demonstration API definition

```yaml
security:
  - ApiKeyAuth: []
  - bearerAuth: []

securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

### Configuration (browser query string, constructor, config.yaml)

```js
{
      spec: string_of_swagger_file,
      dom_id: '#apiRef',
}
```

### Expected Behavior
HTTP Bearer authorization should show up

### Current Behavior
The HTTP Bearer authorization input is showing error `Unknown security definition type HTTP`. This will be fixed by reloading the page.

![Alt Text](http://g.recordit.co/FofWZckOIx.gif)

Below are the errors when Authorize button is clicked
```
1. Warning: Failed prop type: The prop `authSelectors` is marked as required in `t`, but its value is `undefined`.
2. index.js:2178 Warning: Failed prop type: The prop `specSelectors` is marked as required in `t`, but its value is `undefined`.
3. index.js:2178 Warning: Failed prop type: The prop `authActions` is marked as required in `t`, but its value is `undefined`.
4. Warning: Failed prop type: Required prop `definitions` was not specified in `t`.

```
