### ISSUE TITLE
Could not click on the item in the Parameter Content Type box in 3.13.2 -> 3.13.6

### ISSUE THREAD

**Issue by hnthu** [swagger-api/swagger-ui#4485]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  
| Which Swagger/OpenAPI version?  |
| Which Swagger-UI version?       |
| How did you install Swagger-UI? | 
| Which browser & version?        |
| Which operating system?         | 

### Demonstration API definition

When you reference to a json file or yaml file in your main json file or yaml file.
and the reference json file you define a consumes which contains more than one item.
Then you could not chose the other item in the parameter content type

put a $ref in your main.json
```yaml
 "/v1/book": {
        "$ref": "book.json#/buy"
    },
```
and in book.json:
```yaml
{
"post": {
"description": "Book",
"operationId": "buy",
"summary": "Buy a book",
"tags": [
"Book"
],
"consumes": [
"application/json",
"application/xml"
],
"parameters": [
{
"name": "requestBody",
"in": "body",
"description": "Buy a Book",
"required": true
}
]
}
}
```

### Expected Behavior

![image](https://user-images.githubusercontent.com/25275587/39354771-99a187d8-4a35-11e8-94c8-8fa00463e4ee.png)

User could click on the application/xml successfully.

### Current Behavior

User couldn't click on the application/xml. After click on the application/xml the GUI still use application/json.
![image](https://user-images.githubusercontent.com/25275587/39354904-e7d5a51a-4a35-11e8-9231-791e294c9051.png)

### Possible Solution

I thought the bug was happened after the fix for path item $ref rendering (via #4381) in 3.13.2
