### ISSUE TITLE
swagger-ui - ui incorrectly validates field in swagger when using pattern

### ISSUE THREAD

**Issue by felixvolz** [swagger-api/swagger-ui#4573]
### Q&A (please complete the following information)
 - OS: [e.g. macOS] win10
 - Browser: [e.g. chrome, safari] chrome
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets] dist asset
 - Swagger-UI version: [e.g. 3.10.0] 3.10.0
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0] Swagger 2.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
        working_field:
          type: string
          description:  The id of the customer 
          example: 70168
          pattern: '^[\p{Alnum}]{1,10}$'
        broken_field:
          type: string
          description:   The brand in which the customer belongs e.g. UBER
          example: UBER
          default: UBER
          pattern: '^[\p{Alnum}]{1,10}$'
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering

I have attached an example with two fields above. 1) The first 'working_field' I have a pattern and NO default. I see swagger-ui validates this correctly with no issues but doesnt apply the pattern agaisn the example. 2) the second field 'broken_field' has a default value and I can see that swagger-ui tags wtih a error message say 'String does not match pattern'^[\p{Alnum}]{1,10}$' :UBER'. This is incorrect, the string DOES match the patter. 

### To reproduce...

1. Go to '...' Create a swagger and have the two fields I provide as examples
4. When teh UI vaildation triggers yo'll see the error message for 2) above

### Expected behavior

I would expect pattern validation to apply tot he default/example fields correct,
