### ISSUE TITLE
Print json null values correctly in the api documentation panel

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-ui#4578]
_From @specialtactics on May 16, 2018 10:03_

### Q&A (please complete the following information)
 - Method of installation: docker
 - Swagger-Editor version: 3.5.5
 - Swagger/OpenAPI version: OpenAPI 3.0

 ### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
components:
  examples:
    exampleModel:
      value:
        {
            "name": "Adam Jacobson",
            "email": null,
        }
 ```

### Is your feature request related to a problem?
YAML is a superset of JSON and hence supports "null" as a value of a json property. It is actually a fairly common use-case for a field to be null (for example, patch a property as null to remove it, default values being null). 

However the editor will display a null value in a json example as empty object { }, which is not accurate and is very annoying.

### Describe the solution you'd like
Editor to print json null as **null** in the example dialogues - for instance, as it would appear in postman.

### Describe alternatives you've considered
I have not, I think it should be consistent with the json standard and other tools.

### Additional context
None

Thank you

_Copied from original issue: swagger-api/swagger-editor#1758_
