### ISSUE TITLE
Requestbody x-www-form-urlencoded is not properly rendered

### ISSUE THREAD

**Issue by lspvic** [swagger-api/swagger-ui#4643]
### Q&A (please complete the following information)
 - OS: windows
 - Browser: chrome
 - Version: 67
 - Method of installation: dist
 - Swagger-UI version: 3.17.0
 - Swagger/OpenAPI version: OpenAPI 3.0

 ### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
      requestBody:
        description: user info to be filled
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - username
                - name
              properties:
                username:
                  type: string
                  description: user identity
                name:
                  type: string
                  description: user name
                phone_number:
                  type: string
                  pattern: '/\d{11}/'
                  description: phone number
 ```
![_20180613215633](https://user-images.githubusercontent.com/4335658/41356192-f486a800-6f55-11e8-9d7e-6bcaebdfe587.png)
 Swagger-UI configuration options:
 ```js
 SwaggerUI({
   // your config options here
 })
 ```

 ```
 ?yourQueryStringConfig
 ```

### Is your feature request related to a problem?
* property descriptions are not shown
* required properties are not starred
* required properties checking,  string regex pattern checking is not performed when try swagger client

However, parameters are ideally shown. There should be no much difference between parameters and body form data.

**Comment by arlix85** [comment]
Hello, I was about to open a new issue but I've seen this one which is correlated. I would like to integrate Ispvic report with the object-level "example" (as documented here https://swagger.io/docs/specification/adding-examples/#request-response-bodies) which doesn't seem to be supported:

```yaml
         application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                userid:
                  type: string
                  description: the id (or email address) inserted by the user in the login form
                password:
                  type: string
                  format: password
              example:
                userid: test
                password: password
```

Plus, the example is still populated by using the notation inside the properties...
```yaml
              properties:
                userid:
                  type: string
                  description: the id (or email address) inserted by the user in the login form
                  example: test
```
...but in the form the example is always rendered between quotation marks:
![screenshot-gimme5 acomea prv-2018 06 14-12-25-56](https://user-images.githubusercontent.com/36543409/41406924-22f6f0f0-6fce-11e8-9a0b-19db9ba6159c.png)

If something is wrong on my YAML code, please let me know, I wasn't able to correct the issue even with different notations.

Thanks,
Fabio

**Comment by lspvic** [comment]
@arlix85 , what is your required configuration for your schema, and which version is your swagger-ui. In my example, the red star and `required` is not shown.
Thank you.

**Comment by arlix85** [comment]
@lspvic just like "example", "required" is still working if used inside the property, like the old v2 standard:
```yaml
              properties:
                userid:
                  type: string
                  description: the id (or email address) inserted by the user in the login form
                  example: test
                  required: true
```

**Comment by lspvic** [comment]
@arlix85  In OpenAPI 3.0, required is not suitable for properties, there's a required array for properties, like
```yaml
         type: object
              required:
                  - userid
              properties:
                userid:
                  type: string
                  description: the id (or email address) inserted by the user in the login form
                  example: test
```
Thanks.
