### ISSUE TITLE
enum string type field in formData with required=true always send the first value.

### ISSUE THREAD

**Issue by SongJoey** [swagger-api/swagger-ui#4693]
### Q&A (please complete the following information)
 - OS: macOS 
 - Browser: Chrome
 - Version: 63
 - Method of installation: docker
 - Swagger-UI version: latest from docker hub: 2376859c51c8
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
formData field with type:string, required: true and enum fields, whatever you choose, it always send the first enum value.

Example Swagger/OpenAPI definition:

add one field to the official pet store example, whatever you choose, it will always send hello.

```
      - in: formData
        name: type
        type: string
        required: true
        enum:
          - hello
          - world
```

### Expected behavior
swagger-ui will send the enum value I choose instead of the first enum value.

### Screenshots
![image](https://user-images.githubusercontent.com/1330008/42266550-4e2dfc38-7fa9-11e8-8ab2-c3c1f713044f.png)

![image](https://user-images.githubusercontent.com/1330008/42266567-5eeb389c-7fa9-11e8-8e7c-27d7aabbfa9a.png)

I've searched in existing issue but didn't find any useful information. thank you!
