### ISSUE TITLE
Referenced files aren't loaded

### ISSUE THREAD

**Issue by PachowStudios** [swagger-api/swagger-ui#4766]
- OS: [Windows 7]
 - Browser: [chrome]
 - Version: [68]
 - Method of installation: [dist]
 - Swagger-UI version: [3.17.5]
 - Swagger/OpenAPI version: [OpenAPI 3.0]

We have a very large definition and rely on splitting up the paths into multiple files.

This used to work in 3.9.2:
```yaml
paths:
  allOf:
    - $ref: 'common/errors.yaml#/paths'
    - $ref: 'common/versions.yaml#/paths'
    - $ref: 'users/users.yaml#/paths'
    # etc... there's nearly 30 files total
```

Now in the newer versions, swagger just says there's no operations defined.

Attached is a minimal reproduction. If you downgrade it to 3.9.2, it works fine.
[swagger-bug.zip](https://github.com/swagger-api/swagger-ui/files/2233686/swagger-bug.zip)

I believe this is related to the lazy loading behavior introduced in #4248
