### ISSUE TITLE
Missing description for `servers:` definition

### ISSUE THREAD

**Issue by Alevale** [swagger-api/swagger-ui#4802]
### Q&A
 - OS: macOS
 - Browser: chrome
 - Version: 68
 - Method of installation: npm
 - Swagger-UI version: 3.18.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
![screen shot 2018-08-08 at 11 56 42](https://user-images.githubusercontent.com/6860659/43831061-364a5e3e-9b03-11e8-90dd-bff6e050c900.png)

Example Swagger/OpenAPI definition:
```yaml
servers:
- url: https://{customerkey}-{projectkey}.digitalcx.com
  description: The production API server
#  variables:
#    customerkey:
#      default: something
#      description: This is your customer key (provided when the app was setup)
#    projectkey:
#      default: something
#      description: This is your project key (provided when the app was setup)
```

Swagger-UI configuration options:
I am using `swagger-ui-express` but nothing else on the SwaggerUI() function configuration

### Describe the bug you're encountering
I expect the description for the server to be there as defined in OpenApi 3, but instead I don't see anything.
Same is happening when I add the `customerkey` and the `projectkey` fields

### To reproduce...

1. Copy te yaml provided here
2. Open the swagger ui and preview the changes
3. See error

### Expected behavior
I would expect the provided description to be showing up underneath the resource, or at least somewhere in the UI.

### Screenshots
![screen shot 2018-08-08 at 11 56 42](https://user-images.githubusercontent.com/6860659/43831061-364a5e3e-9b03-11e8-90dd-bff6e050c900.png)

### Additional context or thoughts
Could this be a feature non implemented?
Could this be related with `swagger-ui-express`?

Thank you very much
