### ISSUE TITLE
$ref'd securitySchemes aren't loaded

### ISSUE THREAD

**Issue by PachowStudios** [swagger-api/swagger-ui#4813]
### Q&A
 - OS: Windows 7
 - Browser: Chrome
 - Version: 68
 - Method of installation: npm swagger-ui-dist
 - Swagger-UI version: 3.18.1
 - Swagger/OpenAPI version: OAS 3

### Content & configuration
In main file:
```yaml
security:
  - localTestUser: []

components:
  securitySchemes:
    localTestUser: { $ref: 'common/auth.yaml#/components/securitySchemes/localTestUser' }
```

In auth.yaml:
```yaml
components:
  securitySchemes:
    localTestUser:
      type: apiKey
      in: header
      name: X-Test-User
```

Swagger-UI configuration options:
```js
SwaggerUI({
  dom_id: '#swagger-ui',
  deepLinking: true,
  presets: [
    SwaggerUIBundle.presets.apis,
    SwaggerUIStandalonePreset,
  ],
  layout: 'StandaloneLayout',
})
```

### Describe the bug you're encountering
Available authorizations dialog is empty.

### Expected behavior
The localTestUser security scheme should be available in the authorize dialog.

### Screenshots

![image](https://user-images.githubusercontent.com/1417838/44107338-ef3a5b86-9fab-11e8-928f-a936c3f4e5d2.png)
