### ISSUE TITLE
Support for the bearer authentication scheme

### ISSUE THREAD

**Issue by yellowiscool** [swagger-api/swagger-ui#4814]
### Content & configuration

 ```yaml
security:
  - bearerAuth: []

securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
 ```

### Is your feature request related to a problem?

The bearer authentication scheme is not supported yet by swagger-ui. An error warning is displayed instead : `Unknown security definition type HTTP` (as reported in #4481).

### Describe the solution you'd like

Support for the bearer authentication scheme.
