### ISSUE TITLE
Authorization value is lost on refresh

### ISSUE THREAD

**Issue by Vanuan** [swagger-api/swagger-ui#4851]
### Q&A (please complete the following information)
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 68
 - Method of installation: docker hub
 - Swagger-UI version: 3.18.2
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
components:
  securitySchemes:
    x-api-token:
      type: apiKey
      name: x-api-token
      in: header
  links: {}
  callbacks: {}
security:
  - x-api-token: []
```

### Describe the bug you're encountering

Authorization value is lost on refresh

### To reproduce...

1. Click on 'Authorize'
2. Enter value
3. Press 'Authorize'
4. Refresh the page
5. Click 'Authorize' again

### Expected behavior

I should see "Value: ******"

### Screenshots

![screenshot from 2018-09-06 06-26-58](https://user-images.githubusercontent.com/361985/45133455-f00a7880-b19d-11e8-89f7-212110e2aed7.png)
![screenshot from 2018-09-06 06-27-47](https://user-images.githubusercontent.com/361985/45133473-06b0cf80-b19e-11e8-82ae-056ecfd7ea83.png)

### Additional context or thoughts

I thought that's the whole purpose of authorize button - to save user session so that it's not lost on refresh
