### ISSUE TITLE
Can't mount custom swagger API from local to docker

### ISSUE THREAD

**Issue by minhloc2011** [swagger-api/swagger-ui#4890]
### Q&A (please complete the following information)
 - OS: [macOS]
 - Browser: [chrome]
 - Version: [latest]
 - Method of installation: [docker image]
 - Swagger-UI version: [latest]
 - Swagger/OpenAPI version: [OpenAPI 3.0]

### Content & configuration

docker-compose.yml config version `3`
```yml
swaggerui:
      environment:
        - SWAGGER_JSON=/docs/swagger.yaml
      image: swaggerapi/swagger-ui
      volumes:
        - /var/www/app/swagger:/docs
      ports:
      - "9090:8080"
```

### How can we help?

i'm using docker-compose.yml to build swagger-ui and want to synchronize from `/var/www/app/swagger/swagger.yaml` to swagger in container of docker BUT after `docker-compose up -d` the swagger-ui always displays the default swagger `Petstore`. I can't load from my api.
How can i resolve this config?

**Comment by shockey** [comment]
hey @minhloc2011, we recently shipped a few improvements to our Docker image - can you try your docker-compose configuration with the latest version of Swagger UI?

**Comment by henres** [comment]
Can you try ?:
```yaml
swaggerui:
      environment:
          SWAGGER_JSON: "/docs/swagger.yaml"
          URL: ""
      image: swaggerapi/swagger-ui
      volumes:
        - /var/www/app/swagger:/docs
      ports:
      - "9090:8080"
```
