### ISSUE TITLE
Pre-fill the Bearer token with a JWT returned from my server and set Authorized to True

### ISSUE THREAD

**Issue by MisterSchmitz** [swagger-api/swagger-ui#4926]
- Swagger-UI version: 3.19.0
 - Swagger/OpenAPI version: OpenAPI 3.0

Swagger/OpenAPI definition:
```yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

### How can we help?
My api uses Bearer token authentication. If I want to add this token to my api calls, I currently have to click the Authorize button and manually supply the JWT. In my case this token is unknown to the user, so I would prefer to pre-set this value with the JWT returned by my server-side code (specific to the logged-in user). 

Can you help point me to where this value is stored and how it can be set?
