### ISSUE TITLE
Collapsible markdown in descriptions?

### ISSUE THREAD

**Issue by michalrus** [swagger-api/swagger-ui#4977]
### Content & configuration
*n/a*

### Is your feature request related to a problem?
Some of our endpoints have very large descriptions. It would help a lot if we could use collapsible blocks in Markdown, like you can do on GitHub, e.g.:

<details><summary>CLICK ME</summary>
<p>

#### yes, even hidden code blocks!

```python
print("hello world!")
```

</p>
</details>

### Describe the solution you'd like
Swagger-UI’s Markdown parser accepting collapsibles, like the `CLICK ME` one above.

### Describe alternatives you've considered
We’re using sections, but, say, 10 screen heights of text, images etc. is… bad UX.

**Comment by shockey** [comment]
Hmm.. since the functionality is provided by the browser ([most browsers, anyway](https://caniuse.com/#search=details)), this should simply be a matter of adding the `<detail>` and `<summary>` tags to our element whitelist.

I'm prioritizing this, as it's widely helpful and likely easy to implement.

**Comment by michalrus** [comment]
> I'm prioritizing this
Thank you very much! :sparkles:

**Comment by michalrus** [comment]
Wonderful! Thanks. =)

I only had to add this style to make it look sensible:

```css
        details                 { margin:        2em 3em; }
        details       > summary { margin-left:   -1em; font-size: 1.5em; font-weight: bold; }
        details[open] > summary { margin-bottom: 0.667em; }
```

(Forgive me if it’s rubbish, I’m no frontend dev.)
