### ISSUE TITLE
File extension and size validation

### ISSUE THREAD

**Issue by 1nfinite** [swagger-api/swagger-ui#4983]
I am using swagger 2. Is it possible that I have file extension and size validation for file in the swagger itself? Something as follow.

```
 parameters:
         - in: formData
           name: upfile
           type: file
           description: The file to upload.
           maxFileSize: 1024
           allowExtensions: [ '.jpg', '.png']
```
