### ISSUE TITLE
Email and uri format not validated

### ISSUE THREAD

**Issue by 1nfinite** [swagger-api/swagger-ui#4990]
I am using swagger 2 with request of formData as follow.
However the format email and format uri is not validated.
What am i doing it wrong?

```
 parameters:
        - name: email
          in: formData
          required: true
          type: string
          format: email
       - name: profileImageUrl
          in: formData
          required: true
          type: string
          format: uri
        
```
