### ISSUE TITLE
API_URL does not work for v3.19.5

### ISSUE THREAD

**Issue by Behoston** [swagger-api/swagger-ui#5005]
```yaml
  swagger-ui:
    image: swaggerapi/swagger-ui:v3.19.5
    environment:
      - API_URL=/api/swagger.json
    networks:
      - default

```
![obraz](https://user-images.githubusercontent.com/7823689/48032203-02317480-e157-11e8-9c5f-0f441911c254.png)
works fine for v3.19.4
