### ISSUE TITLE
Content-Type: multipart/mixed not working with OpenAPI 3.0 files

### ISSUE THREAD

**Issue by ralfhandl** [swagger-api/swagger-ui#5090]
### Environment
 - OS: Windows 10
 - Browser: Chrome
 - Version: 71.0.3578.98 (Official Build) (64-bit)
 - Method of installation: dist assets
 - Swagger-UI version: 3.20.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### What I want to achieve

Send a multipart/mixed request consisting of individual HTTP requests:

![image](https://user-images.githubusercontent.com/951576/50224310-dc2a0180-039d-11e9-809d-05b466f53806.png)

### Works with Swagger 2.0

[Swagger 2.0: example with `multipart/mixed` request body](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/5fc5b59c7666b38116e345b00dc5ba48c9a220cd/examples/batch.openapi.json#/Batch%20Requests/post__batch)

```yaml
    post:
      consumes:
        - multipart/mixed;boundary=request-separator
      produces:
        - multipart/mixed
      parameters:
        - name: requestBody
          in: body
          description: Batch request
          schema:
            type: string
            example: |-
              --request-separator
              Content-Type: application/http
              Content-Transfer-Encoding: binary

              GET http://services.odata.org/V4/(S(cnbm44wtbc1v5bgrlek5lpcc))/TripPinServiceRW/People HTTP/1.1
              Accept: application/json


              --request-separator--
```

### Can't get similar result with OpenAPI 3.0.0 

Request body of content-type: multipart/mixed with boundary parameter to separate individual requests does not work with OpenAPI 3.0 description of API:

- [OpenAPI 3.0 example with `multipart/mixed` request body](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/oasis-tcs/odata-openapi/5fc5b59c7666b38116e345b00dc5ba48c9a220cd/examples/batch.openapi3.json#/Batch%20Requests/post__batch)

"Try it out" does not work, the request body is form-encoded character for character:
![image](https://user-images.githubusercontent.com/951576/50224263-b7358e80-039d-11e9-96db-75d6a8e04a1b.png)

I get close to the desired result with `multipart/form-data`:

```yaml
    post:
      requestBody:
        content: 
          multipart/form-data: # Media type
            schema:            # Request payload
              type: object
              properties:      # Request parts
                one:            # Part 1 (string value)
                  type: object
                  example: "GET stuff HTTP/1.1\nAccept: application/json\n\n"
                two:       # Part2 (object)
                  type: object
                  example: "GET moreStuff HTTP/1.1\nAccept: application/json\n\n"
            encoding: # The same level as schema
              one: # Property name (see above)
                contentType: application/http  
              two: # Property name (see above)
                contentType: application/http
```

This produces a correct multipart request body, but once I change the content-type to multipart/mixed, the request body is no longer multipart.

### To reproduce...

1. Follow one of the two links above to launch the Petstore version of Swagger UI
2. Click on 'Try it out'
3. Click on 'Execute'
