### ISSUE TITLE
Request parameter examples are not rendered in UI

### ISSUE THREAD

**Issue by palsivertsen** [swagger-api/swagger-ui#5108]
### Q&A (please complete the following information)
 - OS: Linux
 - Browser: Chrome
 - Version: Version 70.0.3538.102 (Official Build) (64-bit)
 - Method of installation: 
```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<title>Public API</title>
		<link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@3/swagger-ui.css"></script>
	</head>
	<body>
		<div id="swagger-ui">
		</div>
		<script src="https://unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
		<script src="https://unpkg.com/swagger-ui-dist@3/swagger-ui-standalone-preset.js"></script>
		<script charset="utf-8">
			window.onload = function() {
				const ui = SwaggerUIBundle({
					url: "/current.yaml",
					dom_id: "#swagger-ui",
					deepLinking: true,
					docExpansion: 'none',
					presets: [
						SwaggerUIBundle.presets.apis,
						SwaggerUIStandalonePreset
					],
					plugins: [
						SwaggerUIBundle.plugins.DownloadUrl
					],
					layout: "StandaloneLayout"
				})

				window.ui = ui
			}
		</script>
	</body>
</html>
```
 - Swagger-UI version: 3
 - Swagger/OpenAPI version: OpenAPI 3.1

### Content & configuration
![image](https://user-images.githubusercontent.com/11890143/50698019-2240bf80-1044-11e9-849c-d7c70fdb7e1f.png)
I expect to see `This is the example value I want to see in the UI` somewhere in the UI

Example Swagger/OpenAPI definition:
```yaml
openapi: "3.0.1"
info:
  title: Bug test
  description: Simple test for parameter description
  version: dev
paths:
  /parameter:
    get:
      summary: Test request
      description: This request should have an example for the "test" parameter
      parameters:
        - name: test 
          in: query
          schema:
            type: string
          description: Show me an example!
          examples:
            simple example:
              summary: Simple example
              value: This is the example value I want to see in the UI
            another:
              summary: Just another example
              value: test 123
      responses:
        "200":
          description: Ok
```

Swagger-UI configuration options:
See above

### Describe the bug you're encountering
When using the `example` property for parameters I expect the examples to be rendered somewhere in the UI

### To reproduce...

1. Open the above yml file in Swagger UI
2. Open the '/parameter' request
No example
3. Click 'Try it out'
No example

### Expected behavior
Examples for the `test` parameter should be shown somewhere in the UI

### Screenshots
See above

**Comment by clockworked247** [comment]
+1 to have this added to the UI.

Right now the "default" property renders in the UI as an example.  For your code it would be:

```
paths:
  /parameter:
    get:
      summary: Test request
      description: This request should have an example for the "test" parameter
      parameters:
        - name: test 
          in: query
          schema:
            type: string
            default: This is the example value I want to see in the UI
          description: Show me an example!
          examples:
            simple example:
              summary: Simple example
              value: This is the example value I want to see in the UI
            another:
              summary: Just another example
              value: test 123
```

As far as I can tell, the examples property does nothing in the UI today.  Per the docs: https://swagger.io/docs/specification/2-0/adding-examples/

I tried it on both the properties and on schema definitions, neither spot rendered examples in the Swagger UI.

The reason why this is important to me is that with examples, I can illustrate multiple example structures for the same param (say, if there's an "options param, whose structure changes depending on the type).

**Comment by funduck** [comment]
@hkosova can you show an _example_ for singular or anybody? That's how it doesn't work:

    openapi: 3.0.2
    info:
      title: Parameter example(s)
      version: '1'
    servers:
      - url: localhost
    paths:
      /nodes:
        get:
          operationId: getNodes
          parameters:
            - name: A
              in: query
              schema:
                type: string
              example: Joe
            - name: B
              in: query
              schema:
                type: string
              examples: 
                joe:
                  summary: name
                  value: Joe
          responses:
            200:
              description: OK

**Comment by hkosova** [comment]
```yaml
      parameters:
        - name: A
          in: query
          schema:
            type: string
          example: Joe    # Parameter-level example
        - name: B
          in: query
          schema:
            type: string
            example: Joe  # Schema-level example
```
By "supported" I mean the `example` values are used as sample values for "try it out".

![OAS3 parameter examples in Swagger UI](https://user-images.githubusercontent.com/8576823/52116326-ec323380-2621-11e9-9cf1-68e993b9b351.png)
