### ISSUE TITLE
OAS 3: oauth2 securityScheme -> description does not appear

### ISSUE THREAD

**Issue by romsDKT** [swagger-api/swagger-ui#5230]
### Q&A 
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
When i set an oauth2 securityScheme the description is not displayed.
An info text is displayed about the scopes (i don't want it to appear)

Example Swagger/OpenAPI definition:
```yaml
components:
  securitySchemes:
    oAuthSample:
      type: oauth2
      description: I WANT THAT TO BE DISPLAYED !!
      flows:
        implicit: 
          authorizationUrl: https://api.example.com/oauth2/authorize
          scopes:
            read_pets: read your pets
            write_pets: modify pets in your account
```

### Describe the bug you're encountering
Description doesn't appear and some infos about scopes are displayed

### To reproduce...

1. Set a securityScheme like in the standard example
2. Click on Authorize
3. The description is not visible and this text is always displayed:
Scopes are used to grant an application different levels of access to data on behalf of the end user. Each API may declare one or more scopes.

API requires the following scopes. Select which ones you want to grant to Swagger UI.

Same behavior if you don't set any scopes.

### Expected behavior
Description should appear
Scopes infos should not appear if i don't want to.

### Screenshots
![bug_oauth_oas3](https://user-images.githubusercontent.com/47742357/54189818-de8a8c00-44b2-11e9-9b4e-09231e8ace76.png)
