### ISSUE TITLE
Using $ref to refer to a parameter under a path item object does not work

### ISSUE THREAD

**Issue by jimcullenaus** [swagger-api/swagger-ui#5249]
### Q&A (please complete the following information)
 - OS: Ubuntu 18.04.1 LTS
 - Browser: Chrome, Firefox
 - Swagger-UI version: 3.20.6
 - Swagger/OpenAPI version: OpenApi 3.0

### Content & configuration

In `openapi.yaml`:

```yaml
paths:
  /v1/users/{userId}:
    $ref: ./paths/user.yaml
```

In `paths/user.yaml`:

```yaml
parameters:
  - $ref: ../components/parameters/UserId.yaml
put:
  requestBody:
    $ref: ../components/requestBodies/PutUser.yaml
  responses:
    '201':
      $ref: ../components/responses/UserPutResponse.yaml

get:
  responses:
    '200':
      $ref: ../components/responses/User.yaml
```

In `components/parameters/UserId.yaml`:

```yaml
name: userId
in: path
required: true
description: A user's user id.
schema:
  type: string
```

It displays fine if placed as a parameter directly under the operation:

```yaml
put:
  parameters:
    - $ref: ../components/parameters/UserId.yaml
...
```

### Describe the bug you're encountering

Path parameters do not show up if imported as part of a Path Item Object if that Path Item Object has itself been imported via `$ref`.

Path parameters *do* show up when placed in a Path Item Object if it is *not* `$ref`ed, or if it is in an Operation object.

No error is appearing in the console or at the top of the page. However, I can make an error appear by changing the `$ref:` to point to `../components/nonsense/UserId.yaml`, implying that the issue is *not* an inability to find the correct file.

### Expected behavior

Parameters should display correctly in all cases:

* When placed directly in a Path Item Object
* When imported via `$ref` in a Path Item Object
* When placed directly in an Operation object
* When imported via `$ref` in an Operation

Currently all but the second bullet point works.

### Screenshots

![image](https://user-images.githubusercontent.com/6212837/54656884-22187200-4b13-11e9-88e4-2d3ddb2fc03b.png)

### Additional context or thoughts

Possibly related to #641?
