### ISSUE TITLE
Validation of uuid without dashes

### ISSUE THREAD

**Issue by bertzor** [swagger-api/swagger-ui#5281]
### Q&A 
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
Swagger/OpenAPI definition:
```yaml
 "parameters": [
                    {
                        "name": "petId",
                        "in": "path",
                        "description": "ID of pet to return",
                        "required": true,
                        "type": "string",
                        "format": "uuid"
                    }]
```
The parameter petId is of type string and format uuid.
When a value of 78aea7e5-97c3-4e77-92ea-d40d6a3a4439 is entered in the swagger ui for parameter petId, the swagger ui works as expected. However, for 78aea7e597c34e7792ead40d6a3a4439, the guid without dashes, the client side validation produces the error: "Value must be a Guid".

### How can we help?
Is there an option to allow an uuid without dashes?
