### ISSUE TITLE
Rendering string:string dictionary example

### ISSUE THREAD

**Issue by propagated** [swagger-api/swagger-ui#5307]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [chrome]
 - Version: [73]
 - Method of installation: [editor.swagger.io]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [OpenAPI 3.0]

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
components:
  schemas:
    Order:
      type: object
      properties:
        testMap:
          type: object
          additionalProperties:
            type: string
          example:
            en-us: Map
            fr: le Map
```

### Describe the bug you're encountering
Per https://swagger.io/docs/specification/data-models/dictionaries/

> Examples of Dictionary Contents
> You can use the example keyword to specify sample dictionary contents:
> 
> type: object
> additionalProperties:
>   type: string
> example:
>   en: Hello!
>   fr: Bonjour!

UI does not render any of these examples, it only shows `{ < * >: String }`

### To reproduce...

1. Go to editor.swagger.io
2. Add a dictionary with examples to a component schema
3. Look at render
4. See no examples

### Screenshots
![dictionary](https://user-images.githubusercontent.com/3504728/56210172-3a50b380-6023-11e9-8016-0d861673359e.png)
