### ISSUE TITLE
[Feature Request] Dark mode

### ISSUE THREAD

**Issue by lonix1** [swagger-api/swagger-ui#5327]
Would be nice to have a dark mode version of the UI.

**Comment by luca0898** [comment]
I was going to open a issue right now on this subject hahaha

**Comment by silverwind** [comment]
Poor man's dark mode:

```css
.swagger-ui {
    filter: invert(88%) hue-rotate(180deg);
}

.swagger-ui .highlight-code {
    filter: invert(100%) hue-rotate(180deg);
}
```

**Comment by KaKi87** [comment]
Yes, but this is a feature request.

**Comment by clementCharasson** [comment]
For those who looking for dark mode in swagger, you can use custom CSS with a stylus plugin.
https://33kk.github.io/uso-archive/?search=swagger

**Comment by KaKi87** [comment]
There's also [Dark Reader](https://github.com/darkreader/darkreader), but this shouldn't prevent Swagger from having a native dark theme ^^

**Comment by jeffersoneagley** [comment]
Yea in my case I could build out an alternative, but swagger-ui-react sets sooooooo many default colors, I'm sure it will be brittle.

**Comment by lonix1** [comment]
Agreed, it must be built-in.

But to get this going, maybe someone has dark mode styles to contribute? I see other apps simply use one of the popular themes floating around, e.g. dracula

**Comment by daniloab** [comment]
Now that have the dark mode, can I disable it?

**Comment by gleb-svechnikov** [comment]
There was an attempt to solve it https://github.com/swagger-api/swagger-ui/pull/5964  but for unknown reason PR was closed.

**Comment by Atulin** [comment]
PR still closed, no other word about it. Dark mode must've killed one of the maintainers' hamster or something.

**Comment by MrMelon54** [comment]
at this point I might as well just make my own openapi compliant spec ui with dark mode supported by default
I don't understand how a developer can make a light mode UI it's literally torture

**Comment by dretax** [comment]
https://github.com/Amoenus/SwaggerDark/

**Comment by OzBob** [comment]
So reading the [PR#5964 comments](https://github.com/swagger-api/swagger-ui/pull/5964#issuecomment-1201535713), the summary is:

> [If you want DarkMode, use a custom plugin.]

Which I believe means use static .css file like this one: https://github.com/Amoenus/SwaggerDark/

Not sure why @tim-lai has left this feature request issue open when it is not going to be worked on.

**Comment by gdibble** [comment]
🙏 Should this ever get traction: How about it just respects the OS setting? _Thanks! :)_

**Comment by landsman** [comment]
This would be awesome. I have to see bright colors at night.

I think that by rewriting CSS to using CSS variables + this media query would make the effect:

```css
:root {
  --background-body: white;
}

body {
  background: var(--background-body);
}

/* override variables for dark mode */
@media (prefers-color-scheme: dark) {
  --background-body: black;
}
```
