### ISSUE TITLE
Allow payload definition for JWT schema

### ISSUE THREAD

**Issue by ugurcemozturk** [swagger-api/swagger-ui#5444]
### Is your feature request related to a problem?
Yes. The clients will be able to know what they expect within the payload of the JWT. It will save time to parse the payload on the client-side.

### Describe the solution you'd like
In the security schemas sections, the developer should be able to provide the JWT payload as another sub-schema.
Something like:
```yaml
 securitySchemes:
    AppJwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
            payload: '#/components/schemas/AppJwtPayload'
  schemas:
    AppJwtPayload:  
      type: object
      properties:
        userId:
          type: string
 ```
Thanks.
