### ISSUE TITLE
Salesforce Token URI doesn't allow OPTIONS method for CORS

### ISSUE THREAD

**Issue by ricxsar** [swagger-api/swagger-ui#5510]
### Q&A (please complete the following information)
 - OS: windows
 - Browser: chrome
 - Version: latest
 - Method of installation: dist assets
 - Swagger-UI version: latest
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

I cannot provide a complete YAML config but I'm only interested on authentication

```
securityDefinitions:
  sf_auth:
    type: "oauth2"
    authorizationUrl: "https://login.salesforce.com/services/oauth2/authorize"
    tokenUrl: "https://login.salesforce.com/services/oauth2/token"
    flow: "accessCode"
    scopes: {}}
```
### Screenshots

![image](https://user-images.githubusercontent.com/8968902/62181874-5173a100-b387-11e9-9636-ee496195f346.png)
![image](https://user-images.githubusercontent.com/8968902/62181960-9bf51d80-b387-11e9-8810-78a2ef37a0af.png)

### How can we help?

Is there any ways to overcome this issue like bypassing the `CORS` checking (OPTIONS request) and go directly to get the access token (POST method)

I also verified that my access keys and credential is correct and working.

Salesforce doesn't support `OPTIONS` method for `CORS` on their authorization endpoints.
See https://developer.salesforce.com/forums/?id=9060G000000XfhRQAS.
