### ISSUE TITLE
[swagger-ui-react] Required headers fail validation (with values)

### ISSUE THREAD

**Issue by pwan001-dev** [swagger-api/swagger-ui#5521]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 76
 - Method of installation: npm
 - swagger-ui-react version: 3.23.4
 - react version: 16.8.6
 - Swagger/OpenAPI version: Swagger 2.0

Example Swagger/OpenAPI definition:
```yaml
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0"
  },
  "host": "foo.bar.com",
  "tags": [
    {
      "name": "foo"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/v1/foo": {
      "get": {
        "tags": [
          "foo"
        ],
        "summary": "sum",
        "description": "desc",
        "operationId": "foo1",
        "parameters": [
          {
            "name": "param1",
            "in": "query",
            "description": "param1",
            "required": true,
            "type": "string",
            "default": "{param1}"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "String",
            "default": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "499": {
            "description": "Application Error"
          },
          "503": {
            "description": "Service Unavailable"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "privateAuthUser": []
          }
        ]
      }
    }
  }
}
```
^ Apologies if this isn't valid, modified to obscure details.

### Describe the bug you're encountering
Swagger definitions that have required **header** fields always fail validation even values are present. It may be related to default header values being provided initially, but changing their values manually doesn't fix the problem.

I have confirmed that required query params work fine.

### To reproduce...
Unfortunately I'm unable to provide a quick test for this as I'm only involved in the UI portion. If required, I can spend time setting up a concrete sample.

### Expected behavior
Required fields (with pre-populated defaults) should Execute without error (given the values are valid).

### Screenshots
![swagger-bug](https://user-images.githubusercontent.com/45157434/62666366-07b32980-b938-11e9-82d3-69f0079a69ef.png)

### Additional context or thoughts
I saw this related issue: https://github.com/swagger-api/swagger-ui/issues/4745
However, it looked like the resolution was to use `swagger-ui-react` which doesn't apply here. If I missed something relevant, apologies.

**Comment by hkosova** [comment]
Your definition is not valid, you need to replace `"type": "String"` with `"type": "string"` (lowercase "s"). "Try it out" should work fine after this fix.

You can use https://editor.swagger.io to check your API definitions for syntax errors.

On an unrelated note, the `Content-Type` and `Accept` headers should be defined by the `consumes` and `produces` keywords rather than header parameters:
```yaml
operationId: something
consumes:
  - application/json   # This is the request's "Content-Type"
produces:
  - application/json   # This is the request's "Accept" header and the response's "Content-Type"
```
