### ISSUE TITLE
Even if 'Try it out' is not clicked enum string values are enabled

### ISSUE THREAD

**Issue by leseb83** [swagger-api/swagger-ui#5568]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Version: latest
 - Method of installation: dist assets
 - Swagger-UI version: 3.23.6
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

We have the following configuration for the 'sort' parameter:
```
in: query
name: sort
description: 'Desc'
schema:
    type: string
     default: name
     enum: [name,createDate,updateDate]
```
![image](https://user-images.githubusercontent.com/51165800/63699228-b2748480-c820-11e9-8613-f7e1230cabf8.png)

All other entries but enum string are disabled as expected.

### Describe the bug you're encountering
Until you press the "Try it out' all fields are supposed to be disabled.

### To reproduce...
See above
