### ISSUE TITLE
Authorization Header issue

### ISSUE THREAD

**Issue by shivaprasad573** [swagger-api/swagger-ui#5715]
I am trying to use the Authorization header in the swagger latest version.
 You can try the above YAML configuration in [Swagger Editor](https://editor.swagger.io/).

You can observe that the Authorization header which I added in the header section is not included in the CURL command.

[openapi.txt](https://github.com/swagger-api/swagger-ui/files/3851566/openapi.txt)

Help me to add an Authorization header into my API.

**Comment by webron** [comment]
The specification does not allow explicitly adding Authorization header. For more information, please read https://swagger.io/docs/specification/describing-parameters/#header-parameters.

**Comment by hkosova** [comment]
The `Authorization` header needs to be defined as a [security scheme](https://swagger.io/docs/specification/authentication/). In your example it should look like this:

```yaml
components:
  securitySchemes:
    auth:
      type: apiKey
      in: header
      name: Authorization

security:
  - auth: []
```
