### ISSUE TITLE
readOnly property is not displayed in object

### ISSUE THREAD

**Issue by CameronGo** [swagger-api/swagger-ui#5793]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Method of installation: docker container
 - Swagger-UI version: 3.23.0 (also confirmed from online editor.swagger.io)
 - Swagger/OpenAPI version:  OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
    TimeStamps:
      type: object
      readOnly: true
      description: 'Basic timestamp object'
      properties:
        created:
          description: The date and time when the record was created
          type: string
          format: datetime
          example: '2015-10-11T17:53:03Z'
          readOnly: true
        updated:
          description: The date and time when the record was last updated
          type: string
          format: datetime
          example: '2015-10-12T16:33:00Z'
          readOnly: true
```
### Describe the bug you're encountering
The schema above renders as follows in the screenshot below.  The readOnly string properties indicate as such for each of the properties, but the readOnly object does not display its readOnly characteristic.

![image](https://user-images.githubusercontent.com/14074983/72292842-3d171e00-3620-11ea-8d6d-acbb258a22b6.png)

### To reproduce...

Place the Timestamps schema referenced above into any OAS3 schema object and then view the rendered schema object in swagger UI.

### Expected behavior
I believe I should expect to see ```readOnly: true``` somewhere within the TimeStamps object itself in addition to on the created and updated properties.

### Additional context or thoughts
I've seen other bugs or requests posted referencing other behaviors related to readOnly properties, but not this specific issue.  From my testing, the Request Body and Response Body rendering is working as expected and observing the readOnly property of the TimeStamps object as expected.  Not displaying readOnly on the object; however, makes it difficult for anyone reading the schema to know that is the case.
