### ISSUE TITLE
How to keep a % character in a swagger's parameter

### ISSUE THREAD

**Issue by MancTwins** [swagger-api/swagger-ui#5802]
Hi everyone,
excuse me if the question is for  beginners' stage but any help is much appreciated.
We want to create a custom connector to access an azure table storage by using a shared access signature (SAS).
Our url is the following: https://ouraccount.file.core.windows.net/?sv=2019-02-02&ss=bfqt&srt=sco&sp=rwdlacup&se=2020-01-17T03:56:52Z&st=2020-01-16T19:56:52Z&spr=https&sig=3ByX21hqo9x521Ia7Nxtm64agBMvzBHoRb2x4Al3NRc%3D
The swagger created after the import of the url is the following (for testing purposes we are passing the values as default)

swagger: '2.0'
info: {version: 1.0.0, title: Azure Table, description: Azure Table}
host: intstorageacctabledev.table.core.windows.net
basePath: /
schemes: [https]
consumes: []
produces: [application/json]
paths:
  /Relationships: {}
  /Relationships/(PartitionKey='59e9efae-2118-ea11-a811-000d3ab9bd1c',RowKey='59e9efae-2118-ea11-a811-000d3ab9bd1c'):
    delete:
      summary: Delete Request
      description: Delete Request
      operationId: DeleteRequest
      parameters:
      - {name: sv, default: '2019-02-02', in: query, type: string, required: true}
      - {name: ss, default: bfqt, in: query, type: string, required: true}
      - {name: srt, default: sco, in: query, type: string, required: true}
      - {name: sp, default: rwdlacup, in: query, type: string, required: true}
      - {name: se, default: '2020-01-31T19:53:45Z', in: query, type: string, required: true}
      - {name: st, default: '2020-01-01T11:53:45Z', in: query, type: string, required: true}
      - {name: spr, default: https, in: query, type: string, required: true}
      - {name: sig, default: KvsqwrqOsWmL4FTTYGIWDeaatc1b%2B8%2BNAs74bmT%2F%2BAU%3D,
        in: query, type: string, required: true}
      - {name: If-Match, in: header, required: true, type: string, default: ' *',
        description: If-Match}
      responses:
        default:
          description: default
          schema: {}
  /Relationships(PartitionKey='7166aec3-221c-ea11-a811-000d3ab9b980',RowKey='7166aec3-221c-ea11-a811-000d3ab9b980'):
    get:
      summary: Get Request
      description: Get Request
      operationId: GetRequest
      parameters:
      - {name: sv, in: query, required: false, type: string, default: '2019-02-02'}
      - {name: ss, in: query, required: false, type: string, default: bfqt}
      - {name: srt, in: query, required: false, type: string, default: sco}
      - {name: sp, in: query, required: false, type: string, default: rwdlacup}
      - {name: se, in: query, required: false, type: string, default: '2020-01-17T03:56:52Z'}
      - {name: st, in: query, required: false, type: string, default: '2020-01-16T19:56:52Z'}
      - {name: spr, in: query, required: false, type: string, default: https}
      - {name: sig, in: query, required: true, type: string, default: '3ByX21hqo9x521Ia7Nxtm64agBMvzBHoRb2x4Al3NRc%3D'}
      responses:
        default:
          description: default
          schema: {}
definitions: {}
parameters: {}
responses: {}
securityDefinitions: {}
security: []
tags: []

When we pass the same parameters in postman it returns correct values, with the url in swagger editor in azure is transformed in https://ouraccount.file.core.windows.net/?sv=2019-02-02&ss=bfqt&srt=sco&sp=rwdlacup&se=2020-01-17T03:56:52Z&st=2020-01-16T19:56:52Z&spr=https&sig=3ByX21hqo9x521Ia7Nxtm64agBMvzBHoRb2x4Al3NRcw%**25**3D

The transformation of the % to %25 has as result an AuthenticationFailed with the message: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

How can we keep the same value for this sig parameter in the swagger?
Kind regards

**Comment by hkosova** [comment]
In your example, the value `KvsqwrqOsWmL4FTTYGIWDeaatc1b%2B8%2BNAs74bmT%2F%2BAU%3D` is the percent-encoded version of `KvsqwrqOsWmL4FTTYGIWDeaatc1b+8+NAs74bmT/+AU=`, and the value `3ByX21hqo9x521Ia7Nxtm64agBMvzBHoRb2x4Al3NRc%3D` is the percent-encoded version of `3ByX21hqo9x521Ia7Nxtm64agBMvzBHoRb2x4Al3NRc=`. Swagger UI automatically endodes query parameter values in requests, so you need to use the original (non-encoded) values when specifying the parameter values in UI.

Also, required parameters [cannot have `default` values](https://stackoverflow.com/q/49570369). You should either either remove the `default` values or make the parameters optional. To specify _example_ values, use `x-example` instead.

```yaml
paths:
  "/Relationships/(PartitionKey='59e9efae-2118-ea11-a811-000d3ab9bd1c',RowKey='59e9efae-2118-ea11-a811-000d3ab9bd1c')":
    delete:
      parameters:
        - ...
        - name: sig
          x-example: KvsqwrqOsWmL4FTTYGIWDeaatc1b+8+NAs74bmT/+AU=
          in: query
          type: string
          required: true

  "/Relationships(PartitionKey='7166aec3-221c-ea11-a811-000d3ab9b980',RowKey='7166aec3-221c-ea11-a811-000d3ab9b980')":
    get:
      parameters:
        - ...
        - name: sig
          in: query
          required: true
          type: string
          x-example: 3ByX21hqo9x521Ia7Nxtm64agBMvzBHoRb2x4Al3NRc=
```
