### ISSUE TITLE
Execute button doesn't work for API with file upload

### ISSUE THREAD

**Issue by Pzixel** [swagger-api/swagger-ui#5821]
### Q&A (please complete the following information)
 - OS: Win 10 x64
 - Browser: chrome
 - Version: 79.0.3945.130 (Official Build) (64-bit)
 - Method of installation: NSwag.AspNetCore package
 - Swagger-UI version: 3.24.3
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
All defaults

Example Swagger/OpenAPI definition:
```yaml
{
  "x-generator": "NSwag v13.2.2.0 (NJsonSchema v10.1.4.0 (Newtonsoft.Json v12.0.0.0))",
  "openapi": "3.0.0",
  "info": {
    "title": "API",
    "version": "v1"
  },
  "servers": [
    {
      "url": "http://localhost:55555"
    }
  ],
  "paths": {
    "/{taskId}": {
      "put": {
        "tags": [
          "Confirm"
        ],
        "operationId": "Confirm_Photo",
        "parameters": [
          {
            "name": "taskId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "guid"
            },
            "x-position": 1
          },
          {
            "type": "file",
            "name": "file",
            "in": "formData",
            "schema": {
              "type": "string",
              "format": "binary",
              "nullable": true
            },
            "nullable": true
          }
        ],
        "responses": {
          "401": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MessageModel"
                }
              }
            }
          },
          "200": {
            "description": ""
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MessageModel"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "MessageModel": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "Message": {
            "type": "string",
            "nullable": true
          }
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "apiKey",
        "description": "Type into the textbox: Bearer {your auth token}.",
        "name": "Authorization",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "Bearer": []
    }
  ]
}
```

Swagger-UI configuration options:

All defaults

### Describe the bug you're encountering
For some reason I execute button doesn't work for an API which contains formData file.

### To reproduce...

1. Serve the `swagger.json` file provided above
2. Fill reqired fields, include file to upload
3. Click execute button

### Expected behavior
Request gets sent

### Additional context or thoughts
I understand that I'm using 3rd party package to serve swaggerUI but I'm pretty sure it's swaggerUI issue rather than some 3rd party library, since i've checked provided `swagger.json` in https://editor.swagger.io/ and got the same results.
