### ISSUE TITLE
defined status messages in swagger model

### ISSUE THREAD

**Issue by StephanKrauss** [swagger-api/swagger-ui#5822]
Hi,

i have a simple beginner question.
I can define the response in the swagger file.
Is there a way to define a collection of status in the response ?
For example:

I have a response with a status progress.
The progress status has same defined status.

- waiting
- in work
- problem
- ...

Can i put this status in the model / response of the swagger file.
I need a good information for the other programmes.

Your sincerly

Stephan

**Comment by hkosova** [comment]
Do you mean an `enum`?

```yaml
MySchema:
  type: object
  properties:
    status:
      type: string
      enum:
        - waiting
        - in work
        - problem
```
If you mean something else, can you provide some examples of the "progress status" responses to better illustrate the use case?
