### ISSUE TITLE
Swagger validation which was working fine day before is now failing validation for type: string, containing example as date value

### ISSUE THREAD

**Issue by nachiketrss** [swagger-api/swagger-ui#5834]
Example Swagger/OpenAPI definition:
```yaml

                    "DateOfDelivery": {
                      "example": "2019-09-26",
                      "type": "string"
                    },
```

### Describe the bug you're encountering
The above is part of my swagger spec, and is getting validated ok in editor.swagger.io

We have release pipelines configured. The task 'API Management - Create or Update API' is used in the azure devops portal to configure the web api. The task's field 'Definition Artifact' is given the path of the swagger spec file.

The pipeline was running OK until before yesterday early morning when we started to get validation errors when the pipeline runs.

Error:
```
2020-02-14T12:21:06.8150207Z Data and type mismatch found. [#/paths/~1order-product/post/responses/200/content/application~1json/schema/properties/DateOfDelivery/example]
@{code=ValidationError; target=representation; message=Parsing error(s): The input OpenAPI file is not valid for the OpenAPI specification https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md (schema https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml).}
```

### Expected behavior
No errors
