### ISSUE TITLE
default:0 for integer type shows empty value in UI.

### ISSUE THREAD

**Issue by dmantampfl** [swagger-api/swagger-ui#5920]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Firefox
 - Version: OAS 3.0
 - Method of installation: bpm
 - Swagger-UI version: latest from gitbub .
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration
When I specify default value as 0 for an integer query parameter, the value is rendered empty. Please see the example below.

Example Swagger/OpenAPI definition:
```yaml
    offsetParam:
      in: query
      name: offset
      required: true
      description: "Offset for pagination"
      schema:
        type: "integer"
        default: 0
```
But when I use the following, I see value as '0' in the UI
```yaml
    offsetParam:
      in: query
      name: offset
      required: true
      description: "Offset for pagination"
      schema:
        type: "integer"
        default: "0"
```

Please let me know if any more details are needed
