### ISSUE TITLE
reference to an external file is unsupported

### ISSUE THREAD

**Issue by greg0ire** [swagger-api/swagger-ui#5966]
### Q&A (please complete the following information)
 - OS: not relevant
 - Browser: not relevant
 - Version: I don't understand…
 - Method of installation: docker
 - Swagger-UI version: 3.25.0
 - Swagger/OpenAPI version: not relevant

### Content & configuration

Example Swagger/OpenAPI definition found at https://swagger.io/docs/specification/using-ref/#allowed-places :
```yaml
    paths:
      /users:
        $ref: '../resources/users.yaml'
      /users/{userId}:
        $ref: '../resources/users-by-id.yaml'
```

### Describe the bug you're encountering
References to external files seem to be unsupported

### To reproduce...

1. Open the your inspector with F12
2. You should see one 404 per external file you reference
3. You will also see errors in SwaggerUI

### Expected behavior
Status code 200, no errors

### Additional context or thoughts
This is because only the main file is linked to the document root:

https://github.com/swagger-api/swagger-ui/blob/ba953aaa9175470fe9412b00b0ba6a8a74f78e08/docker/run.sh#L32-L33

Any file that is referenced is not copied to the document root. I worked around the bug by overriding the Docker command so that it does that copy before running the main process.
