### ISSUE TITLE
CORS issue in oauth2 authorizationCode flow

### ISSUE THREAD

**Issue by aldredb** [swagger-api/swagger-ui#6081]
## Q&A (please complete the following information)
 - OS: [e.g. macOS] macOS
 - Browser: [e.g. chrome, safari] Safari
 - Version: [e.g. 22] 13.1
 - Method of installation: [e.g. npm, dist assets] npm
 - Swagger-UI version: [e.g. 3.10.0] 3.24.3
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0] OpenAPI 3.0.3

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
  securitySchemes:
    oauth:
      type: oauth2
      flows: 
        authorizationCode:
          authorizationUrl: https://XX/authorization 
          tokenUrl: https://XX/token
          scopes: 
            registrar: can register
```

Swagger-UI configuration options:
```js
ui.initOAuth({
    clientId: "XXX",
    clientSecret: "XXX",
    appName: "apitemplate",
    scopeSeparator: " ",
    useBasicAuthenticationWithAccessCodeGrant: 'true',
  })
```

### Describe the bug you're encountering
I used the `authorization_code` grant flow to receive my grant code, however, during token retrieval i received error: `Auth ErrorTypeError: Origin http://localhost:8080 is not allowed by Access-Control-Allow-Origin.`

### Screenshots

![image](https://user-images.githubusercontent.com/45155724/83761181-8d168000-a6a8-11ea-9a83-bdb24e81569d.png)
