### ISSUE TITLE
Handling variables for OAuth2 authorizationUrl, tokenUrl and refreshUrl

### ISSUE THREAD

**Issue by FilippoVigani** [swagger-api/swagger-ui#6218]
When configuring the security like so
```
securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://{auth_environment}.mydomain.com/oauth2/authorize
          tokenUrl: https://{auth_environment}.mydomain.com/oauth2/token
          scopes: 
            openid: OpenId
            email: Email
            profile: Profile
```
And defining the variable like so
```
variables:
      auth-environment:
        default: auth     # Production server
        enum:
          - auth         # Production server
          - staging.auth # Development server
          - dev.auth    
```
It would be nice if the authorizationUrl and tokenUrl included the `auth_environment` variable selected by the user.
