### ISSUE TITLE
Allow sending credentials in request body for OAuth2 client_credentials flow

### ISSUE THREAD

**Issue by MeneDev** [swagger-api/swagger-ui#6220]
As per [2.3.1 of The OAuth 2.0 Authorization Framework](https://tools.ietf.org/html/rfc6749#section-2.3.1) clients may set the parameters `client_id` and `client_secret` in the body of the request. Swagger-UI currently supports only setting those values in the `Authorization` header.

### Describe the solution you'd like
```yaml
components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows: 
        clientCredentials: 
          tokenUrl: https://example.com/token/
          in: body # this defaults to 'header' when omitted, which is equivalent to the current behavior
          scopes: {}
```

### Describe alternatives you've considered
Maybe reusing `in` at that point is not optimal? But I personally think it has a very similar semantic, so I'd prefer using `in`.
