### ISSUE TITLE
Unable to load static UI files

### ISSUE THREAD

**Issue by Fleuv** [swagger-api/swagger-ui#6247]
### Q&A (please complete the following information)
 - OS: 5.7.9-1-MANJARO
 - Browser: firefox
 - Version: 78
 - Method of installation: docker
 - Swagger-UI version: 3.30.0
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Running docker-compose with swagger and nginx, consider the following `docker-compose.yml`:

```yaml
version: '3'

services:
  swagger:
    image: swaggerapi/swagger-ui:v3.30.0
    ...
  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - swagger
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
```

and the following `nginx.conf`:

```
http {
  server {
    listen 80 default_server;
    server_name _;
    location /swagger {
      proxy_pass http://swagger:8080/;
    }
  }
}
```

### Describe the bug you're encountering
When going to http://localhost the html loads fine however the static assets linked from the html don't seem to load. When looking in the network inspector I noticed that the assets are loaded from `localhost/<FILE_NAME>` instead of `localhost/docs/<FILE_NAME>`.

One of the outgoing requests to an asset:
```
GET /swagger-ui.css HTTP/1.1
Host: localhost
User-Agent: Mozilla [REDACTED]
Accept: text/css,*/*;q=0.1
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Referer: http://localhost/swagger
Cache-Control: max-age=0
```

and the response:
```
HTTP/1.1 404 Not Found
Server: nginx
Date: Tue, 21 Jul 2020 07:45:18 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 2439
Connection: keep-alive
Cache-Control: no-store, must-revalidate
ETag: "987-pkNlMUTYJp6pkXv/jlWCJfwNiNM"
```
### To reproduce...

1. Create a local directory with the files described in [Content & configuration](#content-&-configuration).
2. Run `docker-compose up`.
3. Go to http://localhost/docs
4. Confirm that static assets are not being loaded.

### Expected behavior
The files are referred from the base URL and thus properly loaded.

### Additional context or thoughts
I also tried to set the `BASE_URL` environmental variable to `/swagger` and changed the nginx `proxy_pass` to `http://swagger:8080/docs/` however it yielded the same result.
