### ISSUE TITLE
Resolver error when using slashes in shortName attribute

### ISSUE THREAD

**Issue by christiansiewert** [swagger-api/swagger-ui#6281]
Hey, 

I get resolving errors in Swagger UI when I use slashes in the shortName attribute. Are you not allowed to use slashes at this point, or am I doing something else wrong?

![image](https://user-images.githubusercontent.com/33094503/89106124-a416eb80-d427-11ea-9407-6403d8d4382e.png)

![image](https://user-images.githubusercontent.com/33094503/89106128-aaa56300-d427-11ea-80bf-534fbeb7e37e.png)

Best,
Christian

**Comment by hkosova** [comment]
This looks like a question for the API Platform framework, not Swagger UI.
https://github.com/api-platform/api-platform

**Comment by christiansiewert** [comment]
I first thought that it might have more to do with ApiPlatform, but I'm not so sure anymore because they only create OAS documents internally.

The relevant part is the creation of the `$ref` attribute:

```yaml
"responses": {
  "200": {
    "description": "Constraint/Options collection response",
    "schema": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Constraint/Options-constraintOption"
```

This should find elements `definitions` and `Constraint/Options-constraintOption` one after one. The elements are there, but I still get a resolver error.

```yaml
"definitions": {
    "Constraint/Options-constraintOption": {
      "type": "object",
```

```
Resolver error at paths./aaas/field/constraint/options.get.responses.200.schema.items.$ref
Could not resolve reference: #/definitions/Constraint/Options-constraintOption
```

Best,
Christian
