### ISSUE TITLE
Deprecated Object Models not displayed as deprecated

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-ui#6369]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Chrome
 - Version: 
 - Method of installation: 
 - Swagger-UI version: 3.32.5
 - Swagger/OpenAPI version: both Swagger 2.0, OpenAPI 3.0

### Content & configuration

(Add to) Example Swagger/OpenAPI definition:
```yaml
# "components/schema" (OAS3), or "definitions" (OAS2)
    IdentificationProfile:
      type: object
      deprecated: true
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    IDP2:
      type: array
      deprecated: true
      items:
        type: string
```

### To reproduce...

1. Add above snippet to a valid defintion
2. Click on `Models: IdentificationProfile`
3. See lack of `deprecated: true`

### Expected behavior

The object model is shown as deprecated in the SwaggerU

### Screenshots

![bug-ui-6369](https://user-images.githubusercontent.com/12902658/92653949-f0194380-f2a3-11ea-9d23-c2e31db65bab.png)

### Additional context or thoughts

As a comparison, in `Models: IDP2`,  the Array Model properly displays `deprecated: true`
