### ISSUE TITLE
Add autofocus for input field generated by OpenApiSecurityScheme

### ISSUE THREAD

**Issue by Saibamen** [swagger-api/swagger-ui#6395]
Please add `autofocus` for input field generated by `OpenApiSecurityScheme` to focus input after clicking `Authorize` button

**Comment by SoldierCorp** [comment]
Hi!

Is this input that needs the autofocus? 
![image](https://user-images.githubusercontent.com/1775881/95276458-db7f8b00-0810-11eb-9053-8f0af5401a2e.png)

**Comment by Saibamen** [comment]
@SoldierCorp: Yes

**Comment by SoldierCorp** [comment]
I would like to work on this one, but I need the admins to assign it to me.

**Comment by Saibamen** [comment]
Just create a PR: https://github.com/swagger-api/swagger-ui/compare

No need to assign

**Comment by Saibamen** [comment]
My PR: https://github.com/swagger-api/swagger-ui/pull/6483

**Comment by aoyama-val** [comment]
Please support bearer auth as well. Not autofocused in 3.35.2.

```yaml
components:
  securitySchemes:
    idToken: # arbitrary name for the security scheme
      type: http
      scheme: bearer
security:
  - idToken: [] # use the same name as above
```

![スクリーンショット 2020-10-16 11 36 42](https://user-images.githubusercontent.com/13144822/96206647-5c265000-0fa4-11eb-9753-ad529b597a35.png)
