### ISSUE TITLE
Is there a way to reorder the sections inside the Operation Summary?

### ISSUE THREAD

**Issue by Shriram-Balaji** [swagger-api/swagger-ui#6451]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 22
 - Method of installation: npm
 - Swagger-UI version: 3.32.5
 - Swagger/OpenAPI version: Swagger 2.0

Swagger-UI configuration options:
```js
    SwaggerUI({
      spec,
      domNode: swaggerRef.current,
      defaultModelExpandDepth: 10,
      docExpansion: 'full',
      plugins: swaggerPlugins,
      showExtensions: true,
    });
```

### How can we help?

I'd like to render the `Extensions` Row before the `Parameters` section when `Operation` Body is expanded.

I was able to use the `wrapComponent` API to customize how the `Extensions` Row appears, but I'd like to know if there's a straightforward way of modifying the order of the `opblock-sections`, without having to reimplement the `Operation` Component using `wrapComponent`.

**Comment by mathis-m** [comment]
If css is an option for you. Then you just need to inject this little piece of css into your page.
```css
.opblock-body {
  width: 100%;
  display: table;
}
.opblock-body>.opblock-section:last-of-type {
    display: table-header-group;
}
```
