### ISSUE TITLE
Dot in operationId breaks Swagger UI 

### ISSUE THREAD

**Issue by gbisaga** [swagger-api/swagger-ui#648]
We're using a recent version of swagger UI (swagger-ui.js says version 2.1.0).

Condition: I put a dot/period in the operationId. Then open with Swagger UI and click the operation name
Expected result: the operation opens to show parameters and responses
Actual result: Nothing happens. Note: If I click "Expand Operations", the operations open correctly.

Note: If I replace the dots in operationId with underscores, it works fine.

Example:

```
paths:
  /schema/query/com.pearson.plugin.greg.testquery:
    post:
      summary: com.pearson.plugin.greg.testquery
      description: ""
      operationId: com.pearson.plugin.greg.testquery
      ...
```
