### ISSUE TITLE
syntaxHighlight via swagger-config.yaml doesn't apply

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-ui#6545]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: 3.35.2
 - Swagger/OpenAPI version: n/a

### Content & configuration

Example Swagger/OpenAPI definition: any, can use petstore per config below

Swagger-UI configuration options:
```js
SwaggerUI({
  // url: "https://petstore.swagger.io/v2/swagger.json",
  configUrl: "./swagger-config.yaml",
})
```

swagger-config.yaml:
```yaml
---
url: "https://petstore3.swagger.io/api/v3/openapi.json" # <-- just testing that the yaml loads properly
validatorUrl: "https://validator.swagger.io/validator" # <-- just testing that the yaml loads properly
# docExpansion: "none"  # <-- just testing that the yaml loads properly
syntaxHighlight:
  - activated: true
  - theme: "obsidian"

```

### To reproduce...

1. create `swagger-config.yaml` in project root directory, with `syntaxHighlight` fields above
2. instantiate SwaggerUI instance with `configUrl` above
3. run swagger-ui; e.g. local dev
4. Click on any operation, look at a code example
5. notice that there is NO syntax highlight applied, not even the default

### Expected behavior

* SyntaxHighlight theme should be applied when specified (and activated) in `swagger-config.yaml`
* SyntaxHighlight theme should only be disable when `activated: false` in `swagger-config.yaml`

### Additional context or thoughts

`js-yaml` returns the `syntaxHighlight` value as an array, but swagger-ui config expects to set `syntaxHighlight` config option as an object.

from console:
```
syntaxHighlight: Array(2)
  0: {activated: true}
  1: {theme: "obsidian"}
```

in `/src`
https://github.com/swagger-api/swagger-ui/blob/07a0416ff664583ff9f481cae7dace226c9f61ec/src/core/index.js#L140
* in `downloadSpec` method, swagger-ui could force transform `fetchedConfig.syntaxHighlight` from an Array format to Object before using `deepExtend` with `mergedConfig`.

* alternatively, swagger-ui could change its `syntaxHighlight` config format.

**Comment by hkosova** [comment]
@tim-lai it should probably be written as:
```yaml
syntaxHighlight:
  activated: true
  theme: "obsidian"
```
