### ISSUE TITLE
HTML tags in text should be rendered in escaped form

### ISSUE THREAD

**Issue by silverwind** [swagger-api/swagger-ui#6554]
### Q&A (please complete the following information)
 - OS: all
 - Browser: all
 - Version: all
 - Method of installation: all
 - Swagger-UI version: 3.36.0
 - Swagger/OpenAPI version: openapi 3.0.3

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.3
info:
  description: content for <meta name="description"> element
```

### Describe the bug you're encountering

The HTML tag in the text is not being rendered.

### Expected output

````html
<p>content for &lt;meta name=&quot;description&quot;&gt; element</p>
````

### Actual output

````html
<p>text for  element</p>
````

### Additional info

It should probably not be done for all elements, `<img>` for example currently renders unescaped to the DOM as part of Markdown rendering and it should stay that way.

**Comment by hkosova** [comment]
It's not a bug. Descriptions are Markdown, and Markdown supports inline HTML tags and so it parses/renders those tags.

Markdown here in GitHub comments works the same, e.g. if you write
> description: content for &lt;meta name="description"&gt; element

GitHub will render it as:
> description: content for <meta name="description"> element

<br/>

To render the `<` and `>` characters as is, use one of the following:
```yaml
# escape < and > as HTML entities
description: content for &lt;meta name="description"&gt; element

# or format the HTML tag as code
description: content for `<meta name="description">` element
```
