### ISSUE TITLE
Example value is used while a default value is set

### ISSUE THREAD

**Issue by manandre** [swagger-api/swagger-ui#6560]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86
 - Method of installation: dist asset
 - Swagger-UI version: 3.32.5
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
name: until
in: query
description: Date to limit time-travel depth [Optional]
schema:
  type: string
  format: date-time
  default: 
  nullable: true
example: '2020-10-22T10:01:18Z'
```

### Describe the bug you're encountering
When a default value is set in the schema of a query parameter it should be used as _default_ (sic) value in "Try it out" mode even if an example is provided

### To reproduce...
- Open swagger ui
The parameter is displayed with the expected default and example values:
![image](https://user-images.githubusercontent.com/2341261/97190583-2e13ed80-17a6-11eb-8b01-fe908dff73cc.png)
- Enter "Try it out" mode
The `input` field contains the example value as _default_ (sic) value in "Try it out" mode:
![image](https://user-images.githubusercontent.com/2341261/97190738-61ef1300-17a6-11eb-8665-f6901e87ca30.png)

### Expected behavior

The default value should be used (here: `null`)
![image](https://user-images.githubusercontent.com/2341261/97191442-2b65c800-17a7-11eb-8ed1-b2cf97be2e38.png)

### Additional context or thoughts
From https://swagger.io/docs/specification/adding-examples/
> Note: Do not confuse example values with default values. An example illustrates what the value is supposed to be. A default value is what the server uses if the client does not provide the value.
