### ISSUE TITLE
UI does not differentiate AND/OR when Using Multiple Authentication Types

### ISSUE THREAD

**Issue by valdorvaldor** [swagger-api/swagger-ui#6565]
When using multiple securitySchemes the UI still shows `A and B` the same way `A or B`

```
security:    # A OR B
  - A
  - B
```

```
security:    # A AND B
  - A
    B
```

.yaml
```
...
  /api/v1/search/{number}:
    get:
      security: 
        - Account: []
          ApiKey: []
          Token: []
...

components:
  securitySchemes:
    Account:
      type: apiKey
      in: header
      name: account
    ApiKey:
      type: apiKey
      in: header
      name: apikey
    Token:
      type: apiKey
      in: header
      name: token

...
```

This is already reported  #4545 and #6155  but those are closed.

![swagger-ud-bug](https://user-images.githubusercontent.com/44455731/97229538-82b76880-17a6-11eb-852f-0a8d2a34c217.png)

 - OS: Linux
 - Browser: Chrome
 - Version: 86
 - Method of installation: dist assets
 - Swagger-UI version: 3.36.0
 - Swagger/OpenAPI version: OpenAPI 3.0
