### ISSUE TITLE
BASE_URL not used when constructing oauth2RedirectUrl

### ISSUE THREAD

**Issue by mrsegen** [swagger-api/swagger-ui#6591]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86
 - Method of installation: kubectl apply -k ./ (based off of https://github.com/HarryEMartland/swagger-ui-kubernetes-example)
 - Swagger-UI version: I believe v3.36.1 of the image on Docker Hub
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.3
servers:
  - description: "description"
    url: "https://my.url.com/api/"
info:
  description: "description"
  version: "version"
  title: "title"
  contact:
    email: "email"
tags:
  # removed
paths:
  # removed

components:
  securitySchemes:
    tps_auth:
      type: "oauth2"
      flows:
        authorizationCode:
          authorizationUrl: "[authorizationUrl]"
          tokenUrl: "[tokenUrl]"
          scopes:
            write:emailAddresses: "modify emailAddresses for your property"
            read:emailAddresses: "read emailAddresses for your property"
  schemas:
    # removed
```

Swagger-UI configuration options:
```yaml
        env:
        - name: BASE_URL
          value: /swagger-ui
        - name: API_URLS
          value: >-
            [
            {url:'/swagger-ui/apis/my.api.yml',name:'My Application'},
            {url:'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml',name:'Pet Store Example'},
            {url:'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/uspto.yaml',name:'USPTO'}
            ]
```

### Describe the bug you're encountering
After authenticating with the external tool, the redirect is to the following
```
oauth2-redirect.html?state=[OMITTED]&session_state=[OMITTED]&code[OMITTED]
```
instead of 
```
swagger-ui/oauth2-redirect.html?state=[OMITTED]&session_state=[OMITTED]&code[OMITTED]
```
as it should be based on the BASE_URL. Thus, in my particular use, we see a 503 Service Temporarily Unavailable error because the Kubernetes Ingress controller is only set up to forward the `swagger-ui/` path to the Pod/Docker container.

### To reproduce...

1. Select a custom API that has securitySchemes as above.
2. Click Authorize
3. Enter client id and client secret, and continue
4. Log in via the external tool (Keycloak in this case)
5. See a 503 Service Temporarily Unavailable error

### Expected behavior
Swagger UI provides a redirect UI to the external OAuth2 tool that includes the BASE_URL, allowing the browser to be redirected to `swagger-ui/oauth2-redirect.html...` and the browser's session to be authenticated and ready to use the API.

### Additional context or thoughts
Despite this being a Kubernetes deployment, Kubernetes/Kustomize are not needed to witness that the BASE_URL is not included in the [oauth2RedirectUrl](https://github.com/swagger-api/swagger-ui/blob/0a807d6237f59880d34131f66cd4fc542fdaca09/src/core/oauth2-authorize.js#L45).

**Comment by mrsegen** [comment]
...And just as I finished writing up the issue, I realized there is a [OAUTH2_REDIRECT_URL](https://github.com/swagger-api/swagger-ui/blob/6a4e52aadbbd2588975011d779da3844fa010847/docs/usage/configuration.md#L72). This solved the problem. Hoping it helps someone else.

**Comment by mrsegen** [comment]
To be more explicit, this is the new env portion of [the deployment](**url**):

```yaml
     env:
        - name: BASE_URL
          value: /swagger-ui
        - name: OAUTH2_REDIRECT_URL
          value: https://my.documentation.domain.name/swagger-ui/oauth2-redirect.html
        - name: API_URLS
          value: >-
            [
            {url:'/swagger-ui/apis/my.api.yml',name:'My Application'},
            {url:'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml',name:'Pet Store Example'},
            {url:'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/uspto.yaml',name:'USPTO'}
            ]
```
