### ISSUE TITLE
Array values of exploded deepObject query parameter are not URL-encoded

### ISSUE THREAD

**Issue by nebehr** [swagger-api/swagger-ui#6672]
Individual array values of a deepObject query parameter defined with explode = true are not URL-encoded during serialization and sent as is. For example:

```yaml
prop:
      name: prop
      in: query
      schema:
        type: object
        properties:
          myKey: { type: array, items: string }
      style: deepObject
      explode: true
```
with prop set to
```js
{ "myKey": ["aaa+bbb"] }
```
is serialized to "prop[myKey]=aaa+bbb" instead of "prop[myKey]=aaa&2bbbb" and is received on the back end as "prop[myKey]=aaa bbb".

 - Method of installation: dist assets
 - Swagger-UI version: 3.37.2
 - Swagger/OpenAPI version: OpenAPI 3.0
