### ISSUE TITLE
For a POST request, the `Accept` header is sent as `*/*` instead of that specified by my path config

### ISSUE THREAD

**Issue by ChristopherSchultz** [swagger-api/swagger-ui#6826]
For example:
```
paths:
  /foo/bar:
    post:
      parameters:
        accept-json:
          name: Accept
          in: header
          required: true
          enum:
            - application/json
```

If you make this request using "Try it!", both the generated `curl` line and the actual request made by the browser contains the `Accept` header with a value of `*/*`. I could understand if the browser overrides the `Accept` header on the way out, but I would expect the `curl` command to have the expected header value.

**Comment by hkosova** [comment]
The syntax is not quite right. An operation's `parameters` must be a _list/array_ of parameters, not a map.

```yaml
      parameters:
        - name: Accept
          in: header
          required: true
          enum:
            - application/json
```

That said, OpenAPI has special keywords to define the `Accept` values, which you should use instead of a header parameter. In OpenAPI 2.0, it's defined using [`produces` ](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#), which can be set globally or on the operation level. And in OpenAPI 3.0 the `Accept` header is defined as response media types - `responses.<code>.content.<media-type>`, see [here](https://swagger.io/docs/specification/describing-responses/).
