### ISSUE TITLE
query paramter not remove 

### ISSUE THREAD

**Issue by gongul** [swagger-api/swagger-ui#6904]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome 
 - Method of installation: https://unpkg.com/swagger-ui-dist@3.41.1/index.js
 - Swagger-UI version: 3.41.1
 - Swagger/OpenAPI version OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
"/products": {
            "get": {
                "operationId": "products_list",
                "description": "",
                "parameters": [
                    {
                        "in": "query",
                        "name": "is_close",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    {
                        "in": "query",
                        "name": "is_show",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    {
                        "name": "limit",
                        "required": false,
                        "in": "query",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "name": "offset",
                        "required": false,
                        "in": "query",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "in": "query",
                        "name": "service_type",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "enum": [
                                    "APPLE",
                                    "BANANA"
                                ]
                            }
                        },
                        "explode": false,
                        "style": "form"
                    }
                ],
                "tags": [
                    "products"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/PaginatedProductList"
                                }
                            }
                        },
                        "description": ""
                    }
                }
            },
            
```

Swagger-UI configuration options:
```js
const swagger_settings  = {"deepLinking": true}

const ui = SwaggerUIBundle({
  url: "/docs2/schema",
  dom_id: "#swagger-ui",
  presets: [
    SwaggerUIBundle.presets.apis,
  ],
  plugin: [
    SwaggerUIBundle.plugins.DownloadUrl
  ],
  layout: "BaseLayout",
  requestInterceptor: (request) => {
    request.headers["X-CSRFToken"] = "IQFmKVtA2GZ3epq1GQQEm2g065HgqCvoZjfF1P6Ikjut9Krv4jHxmkj57KNGvGp8"
    return request;
  },
  ...swagger_settings
})
    
```

### To reproduce...

The phenomenon that remains in the query param even if you click an item on the parameters query array and remove the item. <br/>

If you run it right away, the query param will not be attached, but if you click and remove service_type parameters once, the query param will be attached with ?service_type=.

### Screenshots

![image1](https://user-images.githubusercontent.com/24261462/106719205-5fbe0f80-6645-11eb-8707-df6d3da29bc9.png)
![image2](https://user-images.githubusercontent.com/24261462/106719211-6187d300-6645-11eb-9b48-90fe54376f67.png)
![image3](https://user-images.githubusercontent.com/24261462/106719227-66e51d80-6645-11eb-988e-00dc3cb6ab00.png)
