### ISSUE TITLE
Support Markdown for tags externalDocs description

### ISSUE THREAD

**Issue by BrandKnew123** [swagger-api/swagger-ui#6907]
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
tags:
  - name: pet
    description: Everything  <br /> about your Pets
    externalDocs:
      description: Find out more about this on our website page you can blah blah blah blah blah blah <br />
      url: 'http://swagger.io'
 ```

### Is your feature request related to a problem?

When creating my documentation I would like the documentation to display my URL on a different line than the description for my external docs. Markdown is supported for the Tag description but this does not seem to work for external docs as seen in my example.
 

### Describe the solution you'd like
Please support the use of Markdown here as well to display documentation appropriately

### Additional context
![Capture](https://user-images.githubusercontent.com/41069757/106810555-21235780-663b-11eb-9439-589a7ac422a4.PNG)
