### ISSUE TITLE
Mark an endpoint as deprecated

### ISSUE THREAD

**Issue by SunSun99** [swagger-api/swagger-ui#6925]
Is it possible to mark an endpoint/controller methid with deprecated? So I can tell the user, not to use this function anymore?

**Comment by mathis-m** [comment]
@SunSun99 
````yaml
/method/some:
  get:
    deprecated: true
````
