### ISSUE TITLE
Support for type=object

### ISSUE THREAD

**Issue by chmac** [swagger-api/swagger-ui#694]
As I read the spec (although I'm not 100% clear) this should be valid swagger (in yaml):

``` yaml
paths:
  /foo:
    parameters:
      - name: body
        in: body
        schema:
          properties:
            foo:
              type: string
              ...
```

However, such a format (when rendered to json) throws an error in swagger-ui. The problem arises in [swagger-client.js on line 552](https://github.com/swagger-api/swagger-ui/blob/cdd02ad8a342fb539cefd8ed9094f7a97c0333e4/lib/swagger-client.js#L552):

```
var innerType = this.getType(param);
```

The problem is that in the example above, `getType()` cannot finds the `schema` value, then calls itself recursively on `param.schema`. But the schema itself does not have a type, and if it does, it would be `type=object`, which is not one of the supported options in the `getType()` function.

Not sure how this will be addressed in swagger-ui, but as I understand the code, swagger-ui doesn't really support the return of JSON bodies using schemas, which seems to be the only option according to the spec.

As an aside, if there is a workaround that would allow us to get our documentation rendered, please let me know, happy to hack something together if it gets the docs in HTML...
