### ISSUE TITLE
Plus sign not showing up in property example

### ISSUE THREAD

**Issue by sertsedat** [swagger-api/swagger-ui#6947]
Hi we have the following Kotlin code 

```kotlin
data class User (
   @get:ArraySchema(schema = Schema(example = "+491607654321"))
   val phoneNumbers: List<String> = emptyList(),
)
```

which generates the correct openapi yaml like this
```yml
components:
  schemas:
    User:
      type: object
      properties:
        phoneNumbers:
          type: array
          items:
            type: string
            example: +491607654321
```
But unfortunately, we don't see the leading `+` sign for the phone number example in Swagger UI.

![image](https://user-images.githubusercontent.com/41687757/108063451-86c00c80-705b-11eb-8334-7e42d87c9a25.png)

What may be the problem?

Q&A 
 - Method of installation: kotlin, mvn, javascript src from https://unpkg.com/swagger-ui-dist/swagger-ui-bundle.js
 - Swagger-UI version:  3.43.0
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0
