### ISSUE TITLE
Repeated nested models are ignored

### ISSUE THREAD

**Issue by chmac** [swagger-api/swagger-ui#697]
Might be related or the same issue as #98.

If I create a generic type like `Phone` and use that within multiple definitions, any use after the first is ignored by swagger-ui. I think it's probably a bug in swagger-client, but couldn't find the repo for that, so filing here.

I think the issue is in [swagger-client.js](https://github.com/swagger-api/swagger-ui/blob/295fa75dc43fe856a3c10581c3dcdac4c8365869/lib/swagger-client.js) relating to `modelsToIgnore`. I guess it's a circular dependency protection, but it might be overly conservative.

I think the following is valid swagger 2.0 yaml, but it won't render properly in swagger-ui ([updated gist](https://gist.github.com/chmac/43bf148f476496b79207)).

```
definitions:
  Pet:
    properties:
      name:
        type: string
      birthday:
        type: integer
        format: int32
      phone:
        $ref: Phone
      owner:
        $ref: Owner
    required:
      - name
      - birthday
      - species
  Phone:
    properties:
      code:
        type: string
      number:
        type: string
  Owner:
    properties:
      name:
        type: string
      phone:
        $ref: Phone
```
