### ISSUE TITLE
Oauth2.0 Implicit flow is not working

### ISSUE THREAD

**Issue by ravaga** [swagger-api/swagger-ui#7180]
### Q&A 
 - Browser: all
 - Method of installation: Docker image
 - Swagger-UI version: swaggerapi/swagger-ui:v3.43.0
 - Swagger/OpenAPI version: OpenAPI 3.0.1

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://oauthUrl/oauth2/authorize
          refreshUrl: https://oauthUrl/oauth2/token
          scopes: {}
```

### Describe the bug you're encountering
When using Oauth2.0 Implicit flow, the authorization flow is carried properly and the Swagger UI shows that the user is authorized. However, if the user tries to make a request, the Swagger UI shows that the token is _undefined_ and the request cannot be carried.

### To reproduce...

1. Press _Authorize_ button
2. Authorize via _implicit flow_
3. Execute a request

### Screenshots
Authorization seems to be OK...
![imagen](https://user-images.githubusercontent.com/19761628/114701229-d3098f00-9d22-11eb-833d-d388c95b0704.png)

... but really the token is not obtained
![imagen](https://user-images.githubusercontent.com/19761628/114701429-18c65780-9d23-11eb-8f51-9a052c44b746.png)
