### ISSUE TITLE
Additional OAuth2 parameters in YAML

### ISSUE THREAD

**Issue by nd1012** [swagger-api/swagger-ui#7216]
- Swagger-UI version: 3.47.1
 - OpenAPI version: 3.0.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
components:
  securitySchemes:
    OAuth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://uri.tld
          authConfigs:
            app: "abc"
```

Swagger-UI configuration options:
```js
      const ui = SwaggerUIBundle({
        url: "https://uri.tld",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout"
      });
```

### How can we help?

I saw it's possible to initialize OAuth2 with a JavaScript method, that allows defining additional OAuth2 query parameters. Is it possible to define additional OAuth2 query parameters in the YAML/JSON configuration file, too? Above you can see what I tried - I also try the key `additionalQueryStringParams` without success.

In addition, `client_id` and `client_secret` that I entered in the Swagger UI authorization dialog are being sent to the server as basic authorization header - but POST parameters are expected. The server receives only the POST parameter `grant_type` with the value `client_credentials` (which is correct so far). Did I do anything wrong?
