### ISSUE TITLE
Auth client_credentials flow /Swagger 

### ISSUE THREAD

**Issue by Nameer-Alkhayyat** [swagger-api/swagger-ui#7233]
Hey, I know this issue is well knowing to the community! But I hope someone found a solution 
I am having an issue authenticating using client_credentials flow and SwaggerUI. For some reason, swagger  securitySchemes won't allow me to add the audience and grant_type as parameters, and without them, I can not really get an access token form Auth0. However, if I use Global Client credentials (without adding audience + grant_types) then I get an opaque access token  but not JWT access token. Any request with opague token will result with the following error! 
 ```  jose.exceptions.JWTError: Error decoding token headers ```

### my securitySchemas
```
 securitySchemes:
    oAuth: 
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth-server.com/oauth/token
```

For more info about opaque tokens see [here](https://community.auth0.com/t/cannot-read-headers-on-tokens/51669)
