### ISSUE TITLE
Enum not showing a select field

### ISSUE THREAD

**Issue by DannyBen** [swagger-api/swagger-ui#736]
It is [my understanding](http://stackoverflow.com/questions/27050635/swagger-ui-parameter-as-list-instead-of-text-input/27058161) that the code below should produce a select field of values to choose from. Right now it generates a text field.

```
paths:
  /users:
    get:
      parameters:
        - name: status
          in: query
          type: string
          enum:
            - online
            - offline
```
