### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nikhilagrawaldotnet** [swagger-api/swagger-ui#7394]
### Q&A (please complete the following information)
 - OS: Win7
 - Browser: Chrome
 - Version: 91.0.4472
 - Project Type - ASP.NET 5.0
 - Method of installation: Nuget Manager in Visual Studio 2019
 - Swagger-UI version: 6.1.4
 - Swagger/OpenAPI version: OpenApi 3.0.1

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
{
  "openapi": "3.0.1",
  "info": {
    "title": "MyAPI",
    "version": "v1"
  },
  "paths": {
    "/api/packages": {
      "get": {
        "tags": [
          "Packages"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Package"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Package"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Package"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "FileData": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "nullable": true
          },
          "path": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "nullable": true
          },
          "size": {
            "type": "integer",
            "format": "int64"
          },
          "hash": {
            "type": "string",
            "nullable": true
          },
          "locator": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "nullable": true,
            "readOnly": true
          },
          "isCompressed": {
            "type": "boolean",
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
      "Package": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "nullable": true
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "version": {
            "type": "string",
            "nullable": true
          },
          "compressedFile": {
            "$ref": "#/components/schemas/FileData"
          },
          "files": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/FileData"
            },
            "nullable": true
          },
          "fileServerUrl": {
            "type": "string",
            "nullable": true
          },
          "timestamp": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  }
}
```

Swagger-UI configuration options:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddSwaggerGen(c => c.SwaggerDoc("v1", new OpenApiInfo { Title = "MyAPI", Version = "v1" });
}

public void Configure(IApplicationBuilder app)
{
    app.UseSwagger();
    app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "MyAPI v1"));
}
```

### Describe the bug you're encountering
We are upgrading from ASP.NET 4.72 to 5.0 and had a GET end point which returns collection of a schema. The older code works with Swashbuckle.AspNetCore v4.0.1 and the latest code has v6.1.4.

The endpoint returns json of 542,580 characters in older version & in latest version fails with message `RangeError: Maximum call stack size exceeded`. The endpoint works from postman in both versions, its in swagger UI that this happens. Also, UI becomes unresponsive and hangs. In logs, the .Net logs says the data is returns in couple of seconds.

```
2021-06-29 15:50:28.2021 INFO [70] [Microsoft.AspNetCore.Hosting.Diagnostics] Request starting HTTP/1.1 GET http://myserver:12912/api/packages - - 
2021-06-29 15:50:28.2021 INFO [70] [Microsoft.AspNetCore.Routing.EndpointMiddleware] Executing endpoint 'MyAPI.PackagesController.Get (MyAPI)' 
2021-06-29 15:50:28.2021 INFO [70] [Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker] Route matched with {action = "Get", controller = "Packages"}. Executing controller action with signature System.Threading.Tasks.Task`1[System.Collections.Generic.IEnumerable`1[MyAPI.Package]] Get() on controller MyAPI.PackagesController (MyAPI). 
2021-06-29 15:50:28.5674 INFO [70] [Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor] Executing ObjectResult, writing value of type 'System.Collections.Generic.List`1[[MyAPI.Package, MyAPI, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]]'. 
2021-06-29 15:50:28.9621 INFO [65] [Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker] Executed action MyAPI.PackagesController.Get (MyAPI) in 757.9003ms 
2021-06-29 15:50:28.9621 INFO [65] [Microsoft.AspNetCore.Routing.EndpointMiddleware] Executed endpoint 'MyAPI.PackagesController.Get (MyAPI)' 
2021-06-29 15:50:28.9621 INFO [65] [Microsoft.AspNetCore.Hosting.Diagnostics] Request finished HTTP/1.1 GET http://myserver:12912/api/packages - - - 200 5042580 application/json;+charset=utf-8 760.1613ms 
```

### To reproduce...

In the latest version, hit an api in swagger UI which return a heavy schema json returning around 0.5 million characters.

### Expected behavior
The endpoint should not fail to return results and should be backward compatible with previous versions.

### Screenshots
New version
![image](https://user-images.githubusercontent.com/26463468/123823281-a9700500-d91a-11eb-80cf-15622dd26a61.png)

Older Version
![Capture_Working_4 0 1](https://user-images.githubusercontent.com/26463468/123823401-c7d60080-d91a-11eb-95d2-dc2c136cade7.JPG)

Postman
![Postman](https://user-images.githubusercontent.com/26463468/123823466-dae8d080-d91a-11eb-9bf0-6bd31ec30ea7.JPG)
