### ISSUE TITLE
Is there any way to configure the content-type in auth

### ISSUE THREAD

**Issue by katesun-roserocket** [swagger-api/swagger-ui#7422]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: Version 91.0.4472.114 (Official Build) (x86_64)
 - Method of installation: npm
 - Swagger-UI version: 3.51.1
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Swagger/OpenAPI definition:
```yaml
  jwt:
    description: ''
    type: apiKey
    name: Authorization
    in: header
  roserocket_auth:
    type: oauth2
    tokenUrl: 'https://auth.roserocket.com/oauth2/token'
    flow: password
```

Swagger-UI configuration options:
```js
import React from 'react';
import SwaggerUI from 'swagger-ui-react';
import 'swagger-ui-react/swagger-ui.css';
import swaggerFile from './swagger.yaml';

const ApiDocsSettings = () => <SwaggerUI spec={swaggerFile} />;

export default ApiDocsSettings;
```

### How can we help?

Is there any way to specify the content-type for authentication? I see that when the request is sent it's set to `application/x-www-form-urlencoded` however I need it to be `application/json`. Unsure whether that's something that is configurable in the definition or through the UI.

Thanks!
