### ISSUE TITLE
Swagger UI: array after deleting all elements remains in the request

### ISSUE THREAD

**Issue by karolpawlowski** [swagger-api/swagger-ui#7450]
### Q&A
 - OS: macOS
 - Browser: chrome
 - Version: 92.0.4515.107
 - Method of installation: Using Pylons/pyramid_openapi3
 - Swagger-UI version: 3.17.1
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
        - name: group_source
          in: query
          description: Filter by group ids
          required: false
          schema:
            type: array
            items:
              type: integer
```

### To reproduce...

1. I have an array[integer] parameter.
2. When I don't set any values it doesn't appear in the request:
![image](https://user-images.githubusercontent.com/2912430/128177657-0b7e6af2-b440-45a4-9f41-1944fd8f113c.png)
![image](https://user-images.githubusercontent.com/2912430/128177677-d88a6eb6-ad4d-415a-a6c2-9c7bd727efe4.png)

3. When I added a param, value properly appears in the request
![image](https://user-images.githubusercontent.com/2912430/128177726-68949c8c-9782-4e29-b784-60985e8c894f.png)
![image](https://user-images.githubusercontent.com/2912430/128177743-36f0a6bb-1ea4-4d59-9c61-fe052744932c.png)

4. When I delete the value and execute again, empty param remains in the request.
![image](https://user-images.githubusercontent.com/2912430/128177797-efcfeff3-a9d6-490c-9007-295b08322aca.png)

### Expected behavior
Array type param shouldn't be passed to a request if there are no values anymore.

### Screenshots
Added in steps to reproduce section.
