### ISSUE TITLE
Set default definition

### ISSUE THREAD

**Issue by esfomeado** [swagger-api/swagger-ui#7511]
### Q&A (please complete the following information)
 - OS: Windows 10
 - Browser: Chrome
 - Version: 93
 - Method of installation: dist
 - Swagger-UI version: 3.51.1
 - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

Swagger-UI configuration options:
```js
SwaggerUI({
      configUrl: "/v3/api-docs/swagger-config",
      dom_id: '#swagger-ui',
      deepLinking: true,
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIStandalonePreset
      ],
      plugins: [
        SwaggerUIBundle.plugins.DownloadUrl
      ],
      layout: "StandaloneLayout"
})
```

### How can we help?
Hello,

I have multiple definitions and they are order by default alphabetically but I would like to put one of them as default when you open the swagger-ui.

Is there any way to do this?

Thanks

**Comment by hkosova** [comment]
Use the [`urls.primaryName`](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#user-content-urls.primaryname) config option. For example:
```yaml
# Your "swagger-config" file

urls:
- name: One
  url: 'https://path/to/api1.yaml'
- name: Two
  url: 'https://path/to/api2.yaml'
urls.primaryName: Two
```
or

```js
  const ui = SwaggerUIBundle({
    urls: [
      {url: "https://path/to/api1.yaml", name: "One"},
      {url: "https://path/to/api2.yaml", name: "Two"},
    ],
    "urls.primaryName": "Two",
   ...
  })
```
