### ISSUE TITLE
`oneOf` / `anyOf` usage with form-based content-type schema

### ISSUE THREAD

**Issue by jacobjmarks** [swagger-api/swagger-ui#7640]
_Originally posted by @jacobjmarks in https://github.com/swagger-api/swagger-ui/issues/3803#issuecomment-965940166_

I am having a similar issue here. See below an example spec in which I am attempting to describe a form which can accept one of two possible schemas:

``` yaml
openapi: 3.0.1
info:
  title: FooBar
  version: 1.0.0
paths:
  /foobar:
    post:
      summary: Summary
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              oneOf:
              - type: object
                properties:
                  Foo:
                    type: string
              - type: object
                properties:
                  Bar:
                    type: string
      responses:
        default:
          description: Description
```

> Please note that the same issue occurs when using a `requestBody/content` type of `multipart/form-data`

This endpoint should expect to receive a body of either `Foo=` or `Bar=`.
This schema causes the following Swagger UI interface to be rendered:

![image](https://user-images.githubusercontent.com/19641427/141227881-e80d3805-af76-4451-9810-3f03fbb75938.png)

This is _not_ correct. It is representing the form as a JSON payload and causes invalid requests to be sent to the endpoint in which the Swagger UI is encoding each character as a separate form value. E.g. sending a value of `hi` would result in the body `0=h&1=i`.

This same issue occurs when using `anyOf`.

When using `allOf`, however, a correct representation is rendered as below:

![image](https://user-images.githubusercontent.com/19641427/141227963-19f881e9-90fb-4bf3-bda8-299bdae3836f.png)

Are there any updates here regarding the support for such `oneOf` and `anyOf` usage? Alternatively; am I incorrectly defining my schema in some way to achieve such usage?

**Comment by eduardoj** [comment]
> Alternatively; am I incorrectly defining my schema in some way to achieve such usage?

Could you try increasing the indentation of the item elements of `oneOf`?

```
            schema:
              oneOf:
                - type: object
                  properties:
                    Foo:
                      type: string
                - type: object
                  properties:
                    Bar:
                      type: string
```
