### ISSUE TITLE
Unexpected defaultModelExpandDepth behavior

### ISSUE THREAD

**Issue by alexrejto** [swagger-api/swagger-ui#8008]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Chrome
 - Version: 100.0.4896.127
 - Method of installation: yarn swagger-ui-react
 - Swagger-UI version:  4.10.3
 - Swagger/OpenAPI version: OpenAPI 2.0.0

### Content & configuration

Example Swagger/OpenAPI definition:
This request body is referenced by a POST request in the request body.
```yaml
    AppCreate:
      additionalProperties: false
      properties:
        name:
          type: string
          example: My First App
          minLength: 3
          maxLength: 255
        description:
          type: string
          example: This is my first App!
          maxLength: 8192
        # TODO: add back in configuration when that feature goes to v2
      required:
        - name
```

Swagger-UI configuration options:
```js
        <SwaggerUI
          url='url'
          docExpansion={'none'}
          deepLinking={true}
          // @ts-expect-error: TS2769 Expected @types issue
          defaultModelRendering="model"
          defaultModelsExpandDepth={-1}
          defaultModelExpandDepth={3} // Issues arise when this is larger than 3
        />
```

### Describe the bug you're encountering

When `defaultModelExpandDepth` is 3 or larger, the requestBody is rendered as below on load. Notably, the string-typed name and description fields are hidden behind the carat.

<img width="338" alt="image" src="https://user-images.githubusercontent.com/71287844/166629991-0deff3fb-2651-4a99-8ab0-fdbeaea89456.png">

Expected rendering, shown below, is only accessible if `defaultModelExpandDepth` is 2 or less.
<img width="539" alt="image" src="https://user-images.githubusercontent.com/71287844/166630089-36cb6076-7080-4827-b453-30ab0de0e120.png">

### Additional context or thoughts

Please let me know if you need any additional information! I am happy to help.
