### ISSUE TITLE
Is it possible to enable JWT authentication using docker-compose?

### ISSUE THREAD

**Issue by boozedog** [swagger-api/swagger-ui#8025]
Right now I don't have any authorize button. I'd like to enable it so that I can paste in my JWT token. Can that be accomplished through config in docker-compose?

Here's my current docker-compose YAML:

```
swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"    
    environment:
      API_URL: https://my-awesome-api.com/
    restart: always
```
