### ISSUE TITLE
Swagger UI is ignoring OpenAPI-spec query parameter

### ISSUE THREAD

**Issue by peteole** [swagger-api/swagger-ui#8041]
Hi,
I am having the issue that when deploying the swagger ui with multiple OpenAPI-specs (so that you need the dropdown menu on the top to select the spec) the query parameter marking the selection in the address bar is totally ignored. The API specs load perfectly and also reflect the selected spec in the address, but when I reload the page the viewer switches back to the first API spec, even though the address bar still indicates another spec should be displayed. Also sharing links to a specific spec does not work due to the issue, however the URL hash works correctly so that the viewer jumps to the right operation of a spec after reload

This issue occurs with the latest docker image, setting the list of loadable specs with a config file URL.

**Comment by peteole** [comment]
By the way my configuration is the following in kubernetes:
```yaml
...
    spec:
      containers:
      - name: swagger-ui
        image: docker.io/swaggerapi/swagger-ui:latest
        imagePullPolicy: Always
        env:
        - name: BASE_URL
          value: /doc/swagger-ui
        - name: CONFIG_URL
          value: https://my-config-url.com
        - name: DEEP_LINKING
          value: 'true'
        - name: FILTER
          value: 'true'
        - name: PERSIST_AUTHORIZATION
          value: 'true'
        ports:
        - name: swagger-ui
          containerPort: 8080
```
So the `DEEP_LINKING=true` works for the first API spec only, but it does not enable me to link a specific operation in a API spec.
