### ISSUE TITLE
Add option to generate CURL in summary if OpenApi definition has examples

### ISSUE THREAD

**Issue by pixellos** [swagger-api/swagger-ui#8050]
### Content & configuration

Swagger/OpenAPI definition:
 ```yaml
{
  "openapi": "3.0.1",
  "info": {
    "title": "Test",
    "description": "Test.",
    "contact": {
      "name": "Test",
      "url": "https://test.com",
      "email": "test@test.te"
    },
    "version": "v1.0"
  },
  "paths": {
    "/api/v1.0/{entityId}/someaction": {
      "get": {
        "tags": [
          "Bucket",
        ],
        "summary": "Some summary.",
        "description": "Sample descript",
        "operationId": "GetBucketDetails",
        "parameters": [
          {
            "name": "entityId",
            "in": "path",
            "description": "The identifier of the entity.",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "example": "ca87606e-c758-46ad-af1e-60c84ffcacef"
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the information about bucket existing in file storage.",
            "content": {
              "application/json": {
                "schema": {
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {}
  }
}
 ```

### Is your feature request related to a problem?
No

### Describe the solution you'd like
If we hit TryItOut and Execute there is sample curl displayed.
If example is present for all required parameters curl can be generated before clicking Execute and be shown, eg below Summary

### Describe alternatives you've considered
Plugin, but from initial testing, whole Operation component needs to be overriden, and it later on would be hard to mantain.

### Additional context
I can prepare PR if You're interested
