### ISSUE TITLE
Wrong display of component 

### ISSUE THREAD

**Issue by Eva-F** [swagger-api/swagger-ui#8052]
### Q&A (please complete the following information)
 - OS:  Win10
 - Browser: chrome,  Firefox
 - Swagger-UI version: 4.11.1
 - Swagger/OpenAPI version:  OpenAPI 3.0

### Content & configuration
  see screenshot

Example Swagger/OpenAPI definition:
```yaml
# your YAML here
```components:
  schemas:
    Point:
      type: array
      items:
        type: integer
        minItems: 2
        maxItems: 2
      description:  point [x,y] (in mm)
    Points:
      type: array
      description: array of [x,y] point (in mm)
      items:
        type: array
        items:
          $ref:  '#/components/schemas/Point'
      minItems: 2
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### Describe the bug you're encountering
Displayed wrong name of component in array of refferenced array

### To reproduce...

1. Use my yaml piece of code

### Expected behavior
Expected Points  = array of [Point]

### Screenshots

![swagger](https://user-images.githubusercontent.com/3242659/172114898-b85bc085-6438-461f-9bc4-e1410de1b72b.png)
