### ISSUE TITLE
OAuth2 OpenAPI example has 'flows' with children but core/components/auth/oauth2.jsx has 'flow' and flat schema

### ISSUE THREAD

**Issue by deckerrob** [swagger-api/swagger-ui#8061]
### Q&A (please complete the following information)
  - Swagger/OpenAPI version: OpenAPI 3.0

### Content & configuration

The oauth2 schema in the OpenAPI 3.x documentation does not match how [swagger-ui/src/core/components/auth/oauth2.jsx](https://github.com/swagger-api/swagger-ui/blob/master/src/core/components/auth/oauth2.jsx#L136-L139) is reading the schema.

Example Swagger/OpenAPI definition (from [https://swagger.io/docs/specification/authentication/oauth2/]):
```yaml
components:
  securitySchemes:
    oAuthSample:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow. [More info](https://api.example.com/docs/auth)
      flows:
        implicit: # <---- OAuth flow(authorizationCode, implicit, password or clientCredentials)
          authorizationUrl: https://api.example.com/oauth2/authorize
          scopes:
            read_pets: read your pets
            write_pets: modify pets in your account
```

### Describe the bug you're encountering

The oauth.jsx code reads the schema as if it looks like this:
```
components:
  securitySchemes:
    oAuthSample:   
        type: oauth2
        description: This API uses OAuth 2 with the implicit grant flow. [More info](https://api.example.com/docs/auth)
        flow: implicit   # <---- OAuth flow(authorizationCode, implicit, password or clientCredentials)
        authorizationUrl: https://api.example.com/oauth2/authorize
        scopes:
          read_pets: read your pets
          write_pets: modify pets in your account
```
and doesn't properly display the component if it like it is in the OpenAPI 3.0 documentation as shown above.

### To reproduce...

1. Set a securityScheme like in the standard example

### Expected behavior

The oauth2 dialog should display properly when the standard example is used.
### Screenshots

Using standard schema:
![image](https://user-images.githubusercontent.com/36427000/172927590-bb416cde-2f1d-47e9-b109-b340a5fff379.png)
Using flattened schema:
![image](https://user-images.githubusercontent.com/36427000/172928032-f68b0b92-9a94-40bb-9e75-080a3f99f314.png)
