### ISSUE TITLE
Request url generated with incorrect format for query parameters of type 'array'

### ISSUE THREAD

**Issue by guybedo** [swagger-api/swagger-ui#810]
It seems the url generated by the swagger-ui interface is incorrect for query parameters with type array.

For example, if we have this get request defined :
```
get:
      parameters:
        - name: fields
          in: query
          required: false
          type: array
          items:
            type: string
          enum: [uid, date, title, description]
```

When swagger-ui generates the url to perform this get request, the 'fields' parameter is encoded as a comma separated values string : ?fields=date%2Ctitle%2Cdescription

![screen shot 2015-01-07 at 15 47 25](https://cloud.githubusercontent.com/assets/5336692/5647245/8c8b3ee4-9684-11e4-9b15-3164d238acf4.png)

This encoding is incorrect, well at least it isn't supported by swagger. 
When the request is sent to the server, swagger sends back a 400 response :

![screen shot 2015-01-07 at 15 41 41](https://cloud.githubusercontent.com/assets/5336692/5647172/c5fb490e-9683-11e4-97dc-5f23e59c5553.png)

Swagger accepts different formats for array parameters : 
```
fields=date&fields=title&fields=description
```
or
```
fields[]=date%2Ctitle%2Cdescription
```
