### ISSUE TITLE
Last-modified response header date-time reformatted in Response headers box

### ISSUE THREAD

**Issue by tomeksamcik** [swagger-api/swagger-ui#8178]
### Q&A (please complete the following information)
 - OS: macOS Monterey 12.4
 - Browser: Chrome
 - Version: 105.0.5195.102 (arm64)
 - Method of installation: docker
 - Swagger-UI version: 4.14.0
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0.0

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
(...)
  200:
     description: (...)
     headers:
        Last-Modified:
           description: Last modification time for all returned reasons for the given page in RFC2616 format.
           schema:
              type: string
              format: date-time
              example: Fri, 27 Sep 2019 11:00:00 GMT
(...)  
```

Swagger-UI is in it's default configuration.

### Describe the bug you're encountering

When testing an endpoint that is returning http `Last-modified` header, in the swagger `Response headers` box, instead of having them displayed raw as they are returned from the server, headers are lowercased (not an issue) and `Last-modified` is reformatted in a way that it no longer conforms to `HTTP-date` format (as specified for ex. in [RFC2616](https://www.rfc-editor.org/rfc/rfc2616#section-3.3.1))

Sending it in this format in `If-Modified-Since` header may then result in ignoring it as that's what http protocol tells to do ([RFC7232](https://www.rfc-editor.org/rfc/rfc7232#section-3.3)).

### To reproduce...

Nothing special:
1. Go to `swagger-ui`
2. Click on `Try it out` and `Execute` request returning `Last-modified`
3. Scroll down to `Response headers`
4. See how `Last-modified` is wrongly formatted

### Expected behavior

Instead of `Fri,20 Jul 2018 20:23:07 GMT`, it should be `Fri, 20 Jul 2018 20:23:07 GMT`

### Screenshots

Server response headers:

<img width="587" alt="Zrzut ekranu 2022-09-9 o 12 31 14" src="https://user-images.githubusercontent.com/2179713/189330707-e1ad0d44-4c41-4398-b484-397c8ebcc9a5.png">

Swagger response headers box:

<img width="664" alt="Zrzut ekranu 2022-09-9 o 12 31 27" src="https://user-images.githubusercontent.com/2179713/189330782-b606ccbd-63c6-42ee-896a-de13e394c988.png">
