### ISSUE TITLE
securitySchemes - Semantic error - Security requirements must match a security definition

### ISSUE THREAD

**Issue by edpahang** [swagger-api/swagger-ui#8238]
- Swagger/OpenAPI version: OpenAPI 3.0.1

Example Swagger/OpenAPI definition:
```yaml
components:
  securitySchemes:
    OAuth2q:
      type: "oauth2"
      flows:
        clientCredentials:
          tokenUrl: "https://api-test.XXXXX.com/oauth/token"
          scopes: {}
```

### Describe the bug you're encountering
- We are required to create 2 securitySchemes for an OAuth2 clientCredentials
- Swagger UI only allow one OAuth2 name
- securitySchemes name is case-sensitive
- securitySchemes will not allow duplicate name
- The same behavior when tested in https://editor.swagger.io/
- We isolated the issue by just using one invalid name (ex: OAuth2q)

### Screenshots
![Screen Shot 2022-10-17 at 10 46 48 AM](https://user-images.githubusercontent.com/59853325/196262732-df68f4ee-1e76-4b54-a12c-59354a45de85.png)

### Additional context or thoughts
Screenshot when trying to remove the arbitrary name:
![Screen Shot 2022-10-17 at 11 18 46 AM](https://user-images.githubusercontent.com/59853325/196263024-dd0d38d3-37d6-4ae7-b63a-cf6fc5049a23.png)
