### ISSUE TITLE
SyntaxHighlight not working with latest swagger-ui

### ISSUE THREAD

**Issue by PriyadarshiniGopalS** [swagger-api/swagger-ui#8304]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: chrome
 - Version: 104.0.xxxxxxx
 - Method of installation: war
 - Swagger-UI version: 4.15.5 and latest
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.0

### Content & configuration
I am running swagger-ui using docker in my local and syntaxHighlighting not working with query-parameters. I tried various approached but not working.
Approach 1: used docker-compose.yaml(below mentioned) and spinup the container using the command  `docker compose up`
```
version: '3'
services:
    swagger-ui:
        ports:
          - 8080:8080
        image: swaggerapi/swagger-ui:v4.15.5
        restart: always
        environment:
                QUERY_CONFIG_ENABLED: "true"
                URLS: "[
                        { url: 'https://petstore.swagger.io/v2/swagger.json', name: 'Petstore' }
                       ]"
```
Approach 2: use docker file and build own image & run the container

Dockerfile will look like
```
FROM swaggerapi/swagger-ui
ENV CONFIG_URL="file:///D:/Argon/Repo/Skyline/SwaggerAPI/swagger-config.json"
ENV QUERY_CONFIG_ENABLED="true"
ENV URLS="[ { url: 'https://petstore.swagger.io/v2/swagger.json', name: 'Petstore' } ]"
```

### Describe the bug you're encountering
I am running swagger-ui using docker in my local and syntaxHighlighting not working with query-parameters. I tried various approached but not working.
Approach 1: used docker-compose.yaml(below mentioned) and spinup the container using the command  `docker compose up`
```
version: '3'
services:
    swagger-ui:
        ports:
          - 8080:8080
        image: swaggerapi/swagger-ui:v4.15.5
        restart: always
        environment:
                QUERY_CONFIG_ENABLED: "true"
                URLS: "[
                        { url: 'https://petstore.swagger.io/v2/swagger.json', name: 'Petstore' }
                       ]"
```
Approach 2: use docker file and build own image & run the container
Dockerfile will look like
```
FROM swaggerapi/swagger-ui
ENV CONFIG_URL="file:///D:/Argon/Repo/Skyline/SwaggerAPI/swagger-config.json"
ENV QUERY_CONFIG_ENABLED="true"
ENV URLS="[ { url: 'https://petstore.swagger.io/v2/swagger.json', name: 'Petstore' } ]"
```

After spinning up the container, I tried accessing the url `http://localhost:8080/?syntaxHighlight=false` , but still syntaxHighlight was enabled.
