### ISSUE TITLE
POST formData not working

### ISSUE THREAD

**Issue by clickslide** [swagger-api/swagger-ui#838]
I'm trying to send a simple string as a POST parameter in swagger 2.0. However, I cannot seem to get it to work.

````
    post:
      summary: POST simple parameter
      description: Test
      consumes:
        - application/x-www-form-urlencoded
      parameters:
         -  name: _method
            in: formData
            type: string
            required: true
            description: testing
````

When I view a log of the $_POST details in my PHP server, the array is empty. It should contain the "_method" parameter. 

Please note that this was found as a bug in the swagger-editor here: https://github.com/swagger-api/swagger-editor/issues/299

I have found the same problem in the swagger-ui. Perhaps I'm missing something?
