### ISSUE TITLE
Swagger UI, try It out button, empty space 280px

### ISSUE THREAD

**Issue by Mishanki** [swagger-api/swagger-ui#8443]
Any version swagger ui

Large empty space when I push `try it out` button with headers `application/json`

```css
.swagger-ui textarea {
      min-height: 280px;
}
```

Example json request body and min-height (Swagger UI):

```json
{
     "some_json": "any_value"
}

# space
# space
# space
# space
# space
```
