### ISSUE TITLE
Nginx doesnt start after updating swagger to the latest version

### ISSUE THREAD

**Issue by RozmarinUS** [swagger-api/swagger-ui#8448]
### Q&A
 - OS: Ubuntu 22
 - Kubelet version: 1.26.1
 - Method of installation: Helm in kubernetes
 - Swagger-UI version: 4.17.1

### The story
After updating to the latest version I got an error:
```
2023/03/06 21:58:17 [emerg] 1#1: socket() [::]:8080 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:8080 failed (97: Address family not supported by protocol)
```
On version 4.16.1 it's works!

### Content & configuration

configuration:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-swagger
  labels:
    app: {{ .Chart.Name }}-swagger
spec:
  replicas: 1
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-swagger
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-swagger
    spec:
      containers:
      - name: {{ .Chart.Name }}-swagger
        image: swaggerapi/swagger-ui
        ports:
          - containerPort: 8080
        env:
          - name: URLS
            value: "[{
              \"url\":\"/api/docs-json\",
              \"name\":\"api\"
            }]"
      - name: nginx
        image: nginx
        volumeMounts:
        - name: config-files
          subPath: nginx.conf
          mountPath: /etc/nginx/nginx.conf
      volumes:
      - name: config-files
        configMap:
          name: {{ .Chart.Name }}-swagger-nginx-conf
```
### Expected behavior
The application should start stably
