### ISSUE TITLE
Not showing proper type in generated document for JsonDocument type.

### ISSUE THREAD

**Issue by vikash-2** [swagger-api/swagger-ui#8613]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]
 - Method of installation: [e.g. npm, dist assets]
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Describe the bug you're encountering
For JsonDocument Type the expected type should be object in swagger documentation but it is creating string as a default.
### To reproduce...
I have a model in C#  which have a type JsonDocument 
```
public record SummerCropCommand
{
    public JsonDocument? SummerLivestockType { get; set; }
    public JsonDocument? SummerGrazingStartDate { get; set; }
    public JsonDocument? SummerCountOfHead { get; set; }
    public JsonDocument? SummerDaysGrazing { get; set; }
}
```
### Expected behavior
 ```
SummerCropCommand:
      type: object
      properties:
        summerLivestockType:
          nullable: true
          type: object
        summerGrazingStartDate:
          nullable: true
          type: object
        summerCountOfHead:
          nullable: true
          type: object
        summerDaysGrazing:
          nullable: true
          type: object
      additionalProperties: false
```
`"summerCrop": {
    "summerLivestockType": {},
    "summerGrazingStartDate": {},
    "summerCountOfHead": {},
    "summerDaysGrazing": {}
  }`

### Current behavior
```
     "SummerCropCommand": {
        "type": "object",
        "properties": {
          "summerLivestockType": {
            "nullable": true
          },
          "summerGrazingStartDate": {
            "nullable": true
          },
          "summerCountOfHead": {
            "nullable": true
          },
          "summerDaysGrazing": {
            "nullable": true
          }
        }
```

`"summerCrop": {
    "summerLivestockType": "string",
    "summerGrazingStartDate": "string",
    "summerCountOfHead": "string",
    "summerDaysGrazing": "string"
  }`
