### ISSUE TITLE
Component schema not rendering in SwaggerUI when specified using $ref

### ISSUE THREAD

**Issue by ghost** [swagger-api/swagger-ui#8671]
### Q&A (please complete the following information)
 - OS: macOS Version 13.3.1 (a) (22E772610a)
 - Browser: 42Crunch OpenAPI Editor, SwaggerUI preview
 - Version: 4.17.0
 - Method of installation: VS Code .dmg > Vs Code Extensions
 - Swagger-UI version: [`"swagger-ui-react": "^4.15.5"`](https://github.com/42Crunch/vscode-openapi/blob/v4.17.0/packages/preview-swaggerui/package.json#LL18C2-L18C2)
 - Swagger/OpenAPI version: 3.0.2

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
{
    "openapi":"3.0.2",
    "info": {
      "title":"API Title",
      "version":"1.0"
    },
    "servers": [
      {"url":"https://api.server.test/v1"}
    ],
    "components": {
        "schemas": {
            "collectionTemplate": {
                "type": "object",
                "properties": {
                    "type": {
                        "enum": ["collection"]
                    },
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "object"
                        }
                    }
                }
            },
            "timestampTemplate": {
                "type": "object",
                "properties": {
                    "timestamp": {
                        "enum": ["timestamp"]
                    }
                }
            },
            "item1": {
                "allOf": [
                    {
                        "$ref": "#/components/schemas/timestampTemplate"
                    },
                    {
                        "type": "object",
                        "properties": {
                            "item1Prop": {
                                "type": "string"
                            }
                        }
                    }
                ]
            },
            "item2": {
                "type": "object",
                "properties": {
                    "item2Prop": {
                        "enum": ["item2Prop"]
                    },
                    "item1Copy": {
                        "$ref": "#/components/schemas/item1"
                    }
                }
            },
            "item2CollectionNotRendered": {
                "allOf": [
                    {
                        "$ref": "#/components/schemas/collectionTemplate"
                    },
                    {
                        "type": "object",
                        "properties": {
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/components/schemas/item2"
                                }
                            }
                        }
                    }
                ]
            },
            "item2CollectionRendered": {
                "allOf": [
                    {
                        "$ref": "#/components/schemas/collectionTemplate"
                    },
                    {
                        "type": "object",
                        "properties": {
                            "items": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "item2Prop": {
                                            "enum": ["item2Prop"]
                                        },
                                        "item1Copy": {
                                            "$ref": "#/components/schemas/item1"
                                        }
                                    }
                                }
                            }
                        }
                    }
                ]
            }
        }
    },
    "paths": {
        "/notrendered": {
            "get": {
                "description": "",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/item2CollectionNotRendered"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/rendered": {
            "get": {
                "description": "",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/item2CollectionRendered"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

Swagger-UI configuration options:
```js
// n/a
```

### Describe the bug you're encountering

One component schema (item2 in example) includes another (item1 in example) as a sub-object in its definition. The item2 schema resolves correctly in the "Schemas" section of the preview, but the reference to item1 defaults to "string" rather than displaying the sub-object in the route response example textbox when added as a $ref. Adding the item2 schema directly rather than referencing it produces the expected result.

### To reproduce...

1. Go to https://editor.swagger.io
2. Copy the example definition into the editor
3. Compare example text for responses of /notrendered and /rendered
4. Compare schemas for item2Collection* > items > item1Copy of item2CollectionNotRendered and item2CollectionRendered in the Schemas section.

### Expected behavior

The response example text for item2CollectionNotRendered and item2CollectionRenderd to match.

### Screenshots

![238069996-eb55920c-4660-4416-a422-ba952fd94527](https://github.com/swagger-api/swagger-ui/assets/31902229/9f60f890-4e41-4f0a-8aca-12166bd2871f)

![238070027-7d5df88c-caf4-499a-aa69-24ad5a73af30](https://github.com/swagger-api/swagger-ui/assets/31902229/31997fe2-f5b3-4dd2-a764-b41b9bac41eb)

![238070045-ec5a8ed6-df0d-4253-ac2c-abfb21daea5f](https://github.com/swagger-api/swagger-ui/assets/31902229/309c0542-7a93-4b36-8e59-e3f1981a209f)

### Additional context or thoughts
Directed here by extension project: 42Crunch/vscode-openapi#222
