### ISSUE TITLE
when declaring path param as global to the path, there is no option to set its value

### ISSUE THREAD

**Issue by borisirota** [swagger-api/swagger-ui#911]
by global to the path I mean to declare the path param like this:
```yaml
  /users/{username}:
    parameters:
      -
        name: username
        in: path
        description: username 
        required: true
        type: string
    get:
        ...
    delete:
        ...
```
and not like this:
```yaml
  /users/{username}:
    get:
        parameters:
          -
            name: username
            in: path
            description: username 
            required: true
            type: string
        ...
    delete:
        parameters:
          -
            name: username
            in: path
            description: username 
            required: true
            type: string
        ...
```

It look like this:
![screen shot 2015-02-05 at 8 29 21 pm](https://cloud.githubusercontent.com/assets/5683472/6066839/d76a11b4-ad78-11e4-855d-be5967bef106.png)

Thanks,
Boris
