### ISSUE TITLE
How to update header values in operations from plugin

### ISSUE THREAD

**Issue by tarach** [swagger-api/swagger-ui#9280]
Hi,
I wrote a plugin that does some custom authentication. Currently I'm using ```requestInterceptor``` to decorate the request with the required auth headers but I would like to to update the schema and change example values of parameters in each operations. So that whenever user will click "Try it out" they will have the authenticated values in the request they will be sending. 

How can I update ```My-Header``` example value on each operation from the plugin context ?
```yaml
parameters:
  - name: My-Header
    in: header
    schema:
      type: string
    example: 'to be replaced'
```

~Thanks
