### ISSUE TITLE
Support configuration per oauth2 flow

### ISSUE THREAD

**Issue by heldersousa-planetpayment** [swagger-api/swagger-ui#9313]
### Content & configuration

Swagger/OpenAPI definition:
Take [https://petstore.swagger.io/v2/swagger.json](https://petstore.swagger.io/v2/swagger.json) as the base definition, with the following security definitions (renamed the existing `implicit` definition and added three more oauth2 definitions):
 ```json
    "securityDefinitions": {
        "api_key": {
            "type": "apiKey",
            "name": "api_key",
            "in": "header"
        },
        "petstore_auth": {
            "type": "oauth2",
            "authorizationUrl": "https://petstore.swagger.io/oauth/authorize",
            "flow": "implicit",
            "scopes": {
                "read:pets": "read your pets",
                "write:pets": "modify pets in your account"
            }
        },
        "petstore_auth_client_credentials": {
            "type": "oauth2",
            "authorizationUrl": "https://petstore.swagger.io/oauth/authorize",
            "flow": "client_credentials",
            "scopes": {
                "read:pets": "read your pets",
                "write:pets": "modify pets in your account"
            }
        },
        "petstore_auth_password": {
            "type": "oauth2",
            "authorizationUrl": "https://petstore.swagger.io/oauth/authorize",
            "flow": "password",
            "scopes": {
                "read:pets": "read your pets",
                "write:pets": "modify pets in your account"
            }
        }
    },
 ```

 Swagger-UI configuration options:
https://github.com/swagger-api/swagger-ui/blob/2e523e1fccd569678414a62d50ebe7b2dffa6626/dev-helpers/dev-helper-initializer.js#L22-L32

### Is your feature request related to a problem?
Given the above OpenAPI spec, the `initOAuth` parameters may not work for a scenario where different flows require different `client_id`. 

For instance, when configuring an application in Auth0, one can choose what `grant_types`/`flows` are allowed for that application
![image](https://github.com/swagger-api/swagger-ui/assets/107053506/4cf47245-8e67-4145-85d0-528798e90eb7)

Yes, we could create an application with all `grant_types` enabled for testing, but that may not be desirable when different types of applications have different behaviours. 
In my view, one should create different application types with just the grant_types that make sense to exist for that application. 
* For example, one could enable `authorization_code` for an SPA app, but it wouldn't make sense to enable `client_credentials` for the same app. 
* Similar logic goes for `client_credentials`, as it would make sense to enable it for `Machine to Machine` application, but not for a SPA application.

![image](https://github.com/swagger-api/swagger-ui/assets/107053506/8c973252-196b-4e10-82e1-83e609b7e80f)

Given the above, I believe SwaggerUI should allow different configurations per flow/grant_type. A similar request was raised in this ticket https://github.com/swagger-api/swagger-ui/issues/4690 and there was even an attempt to tackle this on https://github.com/swagger-api/swagger-ui/issues/4087. The code done by @pablocoberly is a good attempt to solve this issue, but it could still create a scenario where the user selects an application that doesn't support all the flows in the OpenAPI spec. That code could still be useful if one wants to use different applications that support the same set of flows but each application uses a different user database.

### Describe the solution you'd like
A simple way to achieve this is to allow an overwrite of the configuration per flow. For example, and given the example above, one could define the config like this:
```yaml
  ui.initOAuth({
    clientId: "your-client-id",
    clientSecret: "your-client-secret-if-required",
    realm: "your-realms",
    appName: "your-app-name",
    scopeSeparator: " ",
    scopes: "openid profile email phone address",
    additionalQueryStringParams: {},
    useBasicAuthenticationWithAccessCodeGrant: false,
    usePkceWithAuthorizationCodeGrant: false,
    oauth2FlowOverwrites: [
      ["client_credentials", {
        clientId: "your-client-id-that-supports-client_credentials-flow",
        clientSecret: "some-secret"
      }],
     ["password", {
        clientId: "your-client-id-that-supports-password-flow",
        clientSecret: "some-secret"
      }]],
  })
```
The end result would be something like this:
<img width="487" alt="image" src="https://github.com/swagger-api/swagger-ui/assets/107053506/769ad937-ab49-4c27-90df-aed1ca723113">

I created a PR https://github.com/swagger-api/swagger-ui/pull/9312/files with a basic implementation for this functionality just to support the feature request. Code not ready for production!
