### ISSUE TITLE
change request url

### ISSUE THREAD

**Issue by TW-KM** [swagger-api/swagger-ui#9760]
### Q&A (please complete the following information)
 - OS: Windows
 - Browser: Chrome
 - Version: 123
 - Method of installation: docker
 - Swagger-UI version: latest docker 2024/03/27
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration
I mapped a swagger.json to the docker container

docker-compose.yml
```
version: '3.8'

services:
  swagger-secretserver:
    image: swaggerapi/swagger-ui
    container_name: swagger
    restart: unless-stopped
    ports:
      - 10002:8080
    volumes:
      - ./data/swagger.json:/usr/share/nginx/html/swagger.json

    environment:
      - SWAGGER_JSON_URL=swagger.json
```

### How can we help?
If I click on Execute Now the request URL is the IP of the host itself. How can I change that to a different server?
