### ISSUE TITLE
Error message formatting for nested parameters

### ISSUE THREAD

**Issue by glowcloud** [swagger-api/swagger-ui#9774]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Version: 123.0.6312.107
 - Swagger-UI version: 5.13.0
 - Swagger/OpenAPI version: Swagger 2.0, OpenAPI 3.x

### Content & configuration

Example Swagger/OpenAPI definition:
```yaml
{
  "openapi": "3.1.0",
  "info": {
    "title": "Server",
    "version": "0.0.1"
  },
  "paths": {
    "/endpoint": {
      "get": {
        "responses": {},
        "parameters": [
          {
            "name": "param",
            "in": "query",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "a": {
                        "type": "string"
                      },
                      "b": {
                        "type": "number"
                      }
                    }
                  }
                }
              }
            }
          },
          {
            "name": "secondParam",
            "in": "query",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "a": {
                      "type": "object",
                      "properties": {
                        "a": {
                          "type": "object",
                          "properties": {
                            "a": {
                              "type": "string"
                            },
                            "b": {
                              "type": "number"
                            }
                          }
                        },
                        "b": {
                          "type": "number"
                        }
                      }
                    },
                    "b": {
                      "type": "number"
                    }
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}
```

### Describe the bug you're encountering

Errors for nested parameters aren't properly formatted and sometimes show `undefined` string.

<img width="1406" alt="Screenshot 2024-04-03 at 13 15 19" src="https://github.com/swagger-api/swagger-ui/assets/44094416/18fc3056-3080-48a1-ac9f-d5f96014f59e">
<img width="1396" alt="Screenshot 2024-04-03 at 13 15 23" src="https://github.com/swagger-api/swagger-ui/assets/44094416/6d603c29-81fe-4dd5-b35c-6a6df967ceb9">

### Expected behavior

Errors should be formatted in a clear way, ex.
`a.b.c: value must be a string` or `a[b][c]: value must be a string ` or `a: b: c: value must be a string`

They should also not contain the `undefined` string, instead it should be shown without trying to specify the affected value, ex:

<img width="1398" alt="Screenshot 2024-04-03 at 13 26 58" src="https://github.com/swagger-api/swagger-ui/assets/44094416/26500e21-153a-4f6e-8ae5-350791792539">

### Additional context or thoughts

This is a follow up for https://github.com/swagger-api/swagger-ui/pull/9687. The `validationErrors` function should be updated to take nested parameters/errors into account.
